- python/main-classic/platformcode/launcher.py
- python/main-classic/resources/settings.conf
- python/main-classic/resources/settings.xml
añadida funcionalidad en la configuración.
- en los enlaces, los servidores se filtraran tanto por listaBlanca, mostrando sólo los servidores válidos, como por listaNegra, no mostrando los que se encuentren en esta lista
Futuras mejoras:
- añadir los servidores de manera dinamica en la configuración obteniendolos de la carpeta "plugin.video.pelisalacarta\servers"
- añadir un campo de texto para añadir todo el filtro que queramos sin tener que realizar de uno en uno.
- obtener los nombres de los servidores de un array y recorrer los elementos en un bucle para formar la listaBlanca y la listaNegra.
> Filtrado de servidores en la configuración

- python/main-classic/platformcode/launcher.py
- python/main-classic/resources/settings.xml
Sin llegar a la funcionalidad que implemente en la version 3.9 (mas info en: http://www.mimediacenter.info/foro/viewtopic.php?f=14&t=6693#p24305), he añadido un poco mas de proteccion para nuestros menores.
El funcionamiento es el siguiente:
- Para Activar el Modo Adulto, ahora se ha de introducir antes una contraseña (por defecto 1234).
- Al salir de Kodi y volver a entrar por el Modo Adulto se desactiva automaticamente.
Para cambiar la contraseña podeis editar en el archivo resources/settings.xml la linea 14:
```<setting id="enableadultmode" type="bool" label="30002" default="true" enable="eq(-1,1234)" subsetting="true"/>```
> Mejoras en el control parental (modo adulto)

- python/main-classic/platformcode/launcher.py
la versión 4.0.4 la acabo de actualizar por el propio plugin, me da error al no encontrar la referencia de "re", se usa para el añadido de filtrar por servidores, la he añadido y ya tira el plugin.
> Error al iniciar en versión 4.0.4

- python/main-classic/servers/openload.py
Eliminado código innecesario y referencia a librería xbmc para que sea
compatible en todas las plataformas, gracias a divadr, SeiTaN y robalo.
> Fix openload

- python/main-classic/channels/cinetemagay.py
- python/main-classic/channels/filesmonster_catalogue.py
- python/main-classic/resources/settings.xml
- python/main-classic/servers/filesmonster.py
Añade soporte para las cuentas premium de filesmonster para lo que se han modificado los archivos.
resources/setings.xml
servers/filesmonster.py
Usa la API pública de filesmonster para verificar si la cuenta es premium y para recuperar la dirección del vídeo en consecuencia. 
Si el login es incorrecto o la cuenta no es premium aparece el texto correspondiente, devuelto del jsonp de la API en la propia línea de para descargar (no he sabido hacer que aparezca un menú emergente jeje)
- Mejorado el canal Filesmonster catalogue, ahora permite mostar el contenido de carpetas con varios archivos en su interior
channels/filesmonster_calaogue.py
- Mejoras en el canal "cine tema gay", se eliminaron las fuentes no operativas y se añaden nuevas fuentes
channesl/cinetemagay.py
> Añade soporte para cuentas premium de filesmonster, mejoras en el canal Filesmonster Catalogue y cambios en el canal "cine tema gay"

- python/main-classic/channels/inkapelis.json
- python/main-classic/channels/inkapelis.py
- python/main-classic/channels/inkapelis.xml
Corregido por cambios en el enmascaramiento de enlaces de la web, ahora
no es necesario.
Fixed #102
> Fixed #102 - Inkapelis

- python/main-classic/core/logger.py
Al llamar a uno de estos metodos automaticamente insertan en el archivo log las siguientes lineas:
######## ERROR ######## o ######## DEBUG ########
[MODULO.FUNCION] MENSAJE pasado como parametro
Donde MODULO y FUNCION son el modulo (archivo py)  y la funcion o procedimiento desde el que se invoca a logger
El metodo logger.info queda como siempre.
En principio solo es para Kodi, pero si se acepta esta modificacion se podria pasar al resto de plataformas.
> Modificados metodos logger.error y logger.debug.

- python/main-classic/core/downloadtools.py
- python/main-classic/servers/openload.py
-Corregido openload por cambios en la página. (solución gracias al addon Ultimate Whitecream)
-Cambios menores en downloadtools para que no se produzca un error de encode en el logger y para que en el diálogo de descarga solo aparezca la url y no las cabeceras adicionales, ya que impiden leerlo por completo.
> Hotfix_openload

- python/main-classic/servers/cnubis.py
Corregida la url que devuelve para evitar errores en versiones de Kodi 14.2 e inferiores debido a no poder conectarse a direcciones https. Gracias a @juanpintom por [comentarlo](https://github.com/tvalacarta/pelisalacarta/pull/128#issuecomment-181347799)
> Fix cnubis

- python/main-classic/platformcode/launcher.py
Propuesta a raíz de este [tema](http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=7382) para modificar el launcher.py cuando el action es strm_detail o play_from_library. Se cambia el orden, en lugar de buscar primero en el findvideos del canal, se pasa a servertools el server y la url del vídeo y si no los tuviera los buscaría por medio del canal.
> Cambios cuando se reproduce desde strm o desde la librería

- python/main-classic/channels/seriesblanco.py
Fix para un pequeño bug colateral al Fix 'idiomas en la descripcion del capitulo'
https://github.com/tvalacarta/pelisalacarta/commit/df4fde5282d1a65b0d330d2301b22c314920c568#diff-ebceb64991269538a3b9b64f38b39cc5
Ejemplo: Star Trek Enterprise: KeyError: 'es '
> Fix bug colateral Fix idiomas

- python/main-classic/channels/seriesblanco.json
- python/main-classic/channels/seriesblanco.py
- python/main-classic/channels/seriesblanco.xml
Estaba mal puesto el parseo de las descargas (se usaba de nuevo los datos de los streams online, en vez de las descargas)
> Fix descargas seriesblanco

- python/main-classic/core/item.py
Los cambios de ese PR se hicieron para que cuando se reprodujese desde la librería comprobase en un primer momento si el item.server tenía algún valor para así directamente buscar con servertools el enlace al vídeo. El problema es que actualmente el Item.py le da al parámetro server el valor por defecto de "directo" por lo que si se agrega una serie/película a la librería sin especificar el server, éste se guardará como directo en el .strm e intentará buscar el enlace con servertools cuando seguramente no debería.
La idea es cambiar el valor por defecto del server a cadena vacía. Esto no afectaría a la reproducción del vídeo ya que al comienzo de la función play_video de xbmctools, se comprueba si el server="" y en ese caso se le da el valor de directo.
> Referente a PR 163 por cambios en reproducción desde la librería

- python/main-classic/platformcode/xbmctools.py
- python/main-classic/servers/openload.py
A raíz de ver que en el canal pelispedia creado por SeiTaN hay muchos enlaces de openload con subtítulos embebidos en su reproductor, he modificado el conector de openload y xbmctools para añadir esa opción y  se pueda utilizar en otros conectores si se da el caso.
> Subtítulos embebidos en servidores

- python/main-classic/channelselector.py
- python/main-classic/core/updater.py
- python/main-classic/platformcode/launcher.py
- python/main-ui/default.py
He echo una serie de cambios para el updater.py, para que funcione en la versión mediaserver, que da error al comprobar actualizaciones ya que el updater actual esta pensado para kodi
Para que funcione en la versión mediaserver este PR hay que mergearlo en la rama develop y en la rama develop-mediaserver
luego en la rama develop-mediaserver hay que mergear otro PR que he creado que modifica el launcher especifico para mediaserver...
he quitado todo lo relacionado con Kodi del updater, solo comprueba la versión y si hay una versión nueva devuelve el numero de la nueva versión, luego, es cada plataforma que se encarga de mostrar el aviso a su manera, creo que así dará menos problemas
> Mejoras updater.py

- python/version-mediaserver/platformcode/controllers/fileserver.py
- python/version-mediaserver/platformcode/template/page.html
Cambio para poder usar pelisalacarta desde fuera de la red local.
El hosthane lo podemos sacar en la propia web vía javascript, con ello ya se puede conectar desde fuera (obviamente, siempre que estén rederigidos los puertos que sean)
> [mediaserver] Acceder desde fuera de la red local

- python/main-classic/core/channeltools.py
- python/main-classic/platformcode/platformtools.py
- python/main-classic/platformcode/xbmc_config_menu.py
Detectados los siguientes errores:
gracias a @superberny70 por la detección de los fallos y sus correcciones.
> [configuración por canales] - Varias correcciones

- python/main-classic/platformcode/xbmctools.py
Pequeña errata en el import que me he encontrado al probar develop y da error nada más entrar al addon ;)
Aunque no sé si es mejor mantener ese import o no, ya que más abajo se repite...
> Errata en xbmctools

- python/main-classic/servers/realdebrid.py
- python/main-classic/servers/realdebrid.xml
No funcionaba debido a que se ha desactivado la api que se utilizaba por una nueva. Me he estado informando del uso de la nueva api, pero para ello se necesita utilizar el token privado de la cuenta (lo cual no recomiendan) o pedirles acceso a la api como app, así que por ahora no se utiliza, simplemente se loguea y se genera el enlace tal y como se hace desde el navegador.
> Reparado conector realdebrid

- python/main-classic/core/servertools.py
- python/main-classic/resources/settings.xml
- python/main-classic/servers/realdebrid.py
- python/version-mediaserver/resources/settings.xml
- python/version-plex/DefaultPrefs.json
- python/version-xbmc-09-plugin/resources/settings.xml
- Ahora real-debrid devuelve varios enlaces de diferente en los servidores que lo soportan.
- Las credenciales que genera la api se guardan en un json como si fueran un setting de un canal dentro del userdata en la carpeta settings_channels.
- En servertools, se añade una comprobación para no usar real-debrid en otras plataformas distintas a Kodi/Xbmc y mediaserver, además del método antiguo para mostrar mensajes de error que devuelva la api.
- Eliminados de los settings.xml los apartados para usuario y contraseña de real-debrid, y por completo en plex.
> Renovado real-debrid para usar la api por completo

- python/main-classic/channels/filesmonster_catalogue.py
- python/main-classic/servers/filesmonster.xml
- Separado el buscador para cada una de las dos webs, ya que cada una tiene su patrón de búsqueda diferente.
- Solucionado el problema por el que no cargaban las categorías de unusualporn.
- Solucionado el problema por el que no cargaban los vídeos de unusualporn, al necesitar una comprobación previa para detectar la URL de descarga, a diferencia de la otra web.
- Convierte a filesmonster en un canal premium, y no de realdebrid y alldebrid (no soportado por ellos)
> Soluciona diferentes fallos con el canal filesmonster catalogue y el servidor filesmonster

- python/main-classic/platformcode/launcher.py
Se ha reportado en el foro que en algún canal como divxatope da error en la función de findvideos. El motivo es que se intenta descartar el parámetro "title" de infoLabels pero éste no existe y salta este error:
```
plugin.video.pelisalacarta\platformcode\launcher.py", line 233, in run
item.infoLabels.pop('title')
KeyError: 'title'
```
Solucionado añadiendo una comprobación de si existe.
> Fix por error en launcher

- python/main-classic/platformcode/library.py
Se soluciona el error que no permitía iniciar pelisalacarta en linux debido a que no localizaba la librería libsmb al hacer el import en library.py
> Fix #306 Import libsmb en linux

- python/main-classic/platformcode/xbmctools.py
En torrenter no funciona sin el quote. La versión anterior enviaba urls "quoteadas".
> Quote item.url para ¿torrenter?

- python/main-classic/channels/cinefox.py
- python/main-classic/channels/hdfull.py
- python/main-classic/servers/gamovideo.py
- Gamovideo daba error debido al user-agent.
- Reparados en hdfull los enlaces a videomega que es el único servidor que fallaba aparentemente.
- En cinefox la ventana de filtro no permitía recorrer todas las opciones con el teclado.
> Arreglos en gamovideo, hdfull y cinefox

- python/main-classic/platformcode/library.py
Cuando llamo de forma externa (vía cron) a la actualización de addons, su nombre es "default.py", por lo que jode todos los strm (pone como addon default.py?URI)
> Reemplazar default.py

- python/main-classic/servers/openload.py
Debido a un cambio en la url que devuelve tras el aadecode.
> Reparado openload

- python/main-classic/core/item.py
- python/main-classic/core/tmdb.py
- python/main-classic/platformcode/launcher.py
- python/main-classic/platformcode/xbmc_info_window.py
- python/main-classic/platformcode/xbmctools.py
item: Ahora no se almacenan datos en los atributos contentXXX, sino q se utiliza el infolabel apropiado para ello.
tmdb: Corregidos errores al buscar listados de modo concurrente. Gracias a @CmosGit
launcher: Solucionado bug #348
xbmctools: Se fija un solo metodo para añadir informacion al listitem. Los antiguos metodos quedan descartados
> Correccion de errores varios en la creacion y gestion de infolabels

- python/main-classic/channels/ayuda.py
- python/main-classic/channels/hdfull.py
- python/main-classic/channels/hdfull.xml
- python/main-classic/core/servertools.py
- python/main-classic/lib/jjdecode.py
- python/main-classic/servers/flashx.py
- python/main-classic/servers/openload.py
- python/main-classic/servers/realdebrid.py
- python/main-classic/servers/thevideome.py
- python/version-command-line/resources/settings.conf
- python/version-plex/DefaultPrefs.json
He incluido en el canal ayuda una opción para activar real-debrid en plataformas distintas a Kodi a través de itemlists en lugar de diálogos. El proceso es el mismo solo que depende de que el usuario interaccione (en Kodi en cuanto detecta la introducción del código se cierra la ventana automáticamente).
Solo lo he probado en plex (versión web), pero no creo que haya problemas para el resto.
- Reparado openload, flashx y thevideome.
- Añadida librería jjdecode para openload.
> Real-debrid en plataformas no kodi - Fix hdfull para plex - Fix openload/Flashx

- python/main-classic/channels/configuracion.py
- python/main-classic/core/downloadtools.py
- python/main-classic/core/ziptools.py
- python/main-classic/platformcode/launcher.py
- python/main-classic/servers/streaminto.py
- Se añade la opción en el canal de configuración para instalar o actualizar canales o conectores a través de una url. Está pensado tanto para enlaces directos de github (raw), como para archivos comprimidos adjuntados en el foro. Estos últimos deben tener los archivos a copiar en la raíz o dentro de la carpeta channels o servers correspondiente, sino no serían válidos.
Además de detectar y avisar si el archivo ya existe para sobrescribirlo, en este caso se hace antes una copia de seguridad del mismo y se guarda en la carpeta userdata/backups, para así evitar posibles errores y poder volver a la versión anterior. Para todo esto se han modificado los archivos de configuracion, downloadtools y ziptools. Lo he testeado exhaustivamente, pero si algún lo prueba y ve algún error comentádmelo.
- …
> Añadida opción en menú configuración - Propuesta para mensajes de error - Reparado streaminto

- python/main-classic/channels/mejortorrent.py
La regex devolvía números incorrectos (014) en títulos como 4x01 al
4x10.
Ahora toma el primer número a partir de la primera x
> Arreglar regex en nombres con varios capítulos

- python/main-classic/channels/buscador.py
- python/main-classic/channels/pornhub.py
Este PR soluciona 2 problemas en el buscador:
1. Las búsquedas se guardaban con el carácter "+" en vez de espacio.
2. El buscador se quedaba colgado cuando tenias los canales adultos activos y el canal "PornHub" en la lista de canales del buscador (por defecto incluido) debido a un error en el patrón del canal PornHub, que misteriosamente para mi, a demás de hacer que el canal no encontrara resultados, dejaba (por lo menos en kodi) el programa colgado. impidiendo que la búsqueda finalizara y teniendo que reiniciar kodi
He echo varias búsquedas con todos los canales activos y ahora ya finaliza sin ningún problema.
> Solucionado problema en Buscador

- python/main-classic/core/channeltools.py
jsontools.load_json devuelve "" en caso de error y no un dict.
Comprobarlo antes de leer del dict.
Me ha cascado al estar jugando con la búsqueda y se ha generado un archivo json que no se podía leer correctamente
> Error al leer archivos json de canal corrompidos

- python/main-classic/channels/allpeliculas.py
- python/main-classic/channels/cinefox.py
- python/main-classic/channels/cinetux.py
- python/main-classic/channels/descargasmix.py
- python/main-classic/channels/gnula.py
- python/main-classic/channels/inkapelis.py
- python/main-classic/channels/newpct1.py
- python/main-classic/channels/pelisdanko.py
- python/main-classic/channels/pordede.py
- python/main-classic/channels/seriecanal.py
- python/main-classic/channels/trailertools.py
- python/main-classic/channels/verseriesynovelas.py
- python/main-classic/channels/zpeliculas.py
Arreglado trailertools a raíz de los cambios en el PR #415
Adaptados los menús contextuales de extendedinfo y buscar trailer en los canales que los utilizaban y añadidos en algunos que no lo tenían.
> Canales adaptados al uso de extendedinfo y trailertools

- python/main-classic/channels/tengourl.py
He añadido dos nuevas opciones en el canal tengourl para complementar a la ya existente que solo busca urls coincidentes entre los conectores. Por un lado una para enlaces directos a un vídeo (mp4, m3u8, etc...) y por otro para buscar enlaces en una página concreta, lo cual puede venir bien para páginas que no tienen un canal propio, para hacer pruebas sin necesidad de navegar por el canal, etc...
> Nuevas opciones en canal tengourl

- python/main-classic/channels/buscador.py
- Por un lado, solo realizaba búsquedas en aquellos canales que en su mainlist tenían un item con un action="search", pero hay canales, como el caso de cinefox, que el método search no está en su mainlist, sino que se ejecuta a través de otro método, pero mientras el canal esté configurado para incluirse en la búsqueda global, debería poder ejecutarse.
- Por otro, en la configuración para elegir los canales incluidos, no salían aquellos cuyo valor en include_global_search no está encapsulado en su xml dentro de `<settings></settings>`, por lo tanto no hay manera de desactivarlos/activarlos desde la ventana.
> Reparados dos fallos en el buscador global

- python/main-classic/channels/biblioteca.py
Desde la biblioteca, si desde tmdb no existe titulo traducido del episodio se muestra el "title" del video encontrado en el servidor
Fix, para que si no hay titulo se muestre un titulo por defecto.
> fix al mostrar titulo al reproducir episodio

- python/main-classic/channels/animeflv_me.py
Pasaron el código del reproductor y los enlaces a los vídeos a un iframe y el canal era incapaz de obtenerlos.
Issue asociada: #439
> Arreglado canal Animeflv.me

- python/main-classic/channels/filtertools.py
- python/main-classic/channels/seriesblanco.py
- python/main-classic/channels/seriesdanko.py
- python/main-classic/core/logger.py
- python/main-classic/platformcode/platformtools.py
Se encapsula filtertools para que sea menos invasivo y más adaptable a los canales.
- cambio en el modo de mostrar la opción de filtros para hacerlo más simple.
- se carga variable de filtertools para mostrar o no el contexto.
- se mueve el método del contexto a su canal y sea genérico.
- se elimina referencia de platformtools.
Se modifica logger para permitir llamar a las funciones sin argumento por comodidad, gracias a la modificación de divadr aparecerá el fichero y método desde el que se llama.
```python
def mainlist(channel):
logger.info()
logger.info("info")
logger.debug()
logger.debug("debug")
logger.error()
logger.error("error")
```
> 09:25:45 T:13320  NOTICE: pelisalacarta.channels.renumeratetools.mainlist
> 09:25:45 T:13320  NOTICE: pelisalacarta.channels.renumeratetools …
> Mejoras en filtertools y logger

- python/main-classic/platformcode/mct.py
Añadiendo esas 2 líneas al bucle de búsqueda de metadatos del magnet la captura se hace al instante. Sin esas líneas, al menos a mí, me tarda una eternidad según le de (a veces más de 1 minuto)  y supongo que como máximo tardará 15 minutos. En cualquier caso da la impresión de estar bloqueado sin hacer nada.
También he aprovechado y quitado los dominios que no resolvían.
fixes #458
> Forzar el anuncio del magnet para capturar los metadatos al instante

- python/main-classic/core/logger.py
Tras los últimos cambios, la navegación por pelisalacarta se había vuelto lenta con el debug activado, sobre todo en funciones que hacían mucho uso del logger, tras hablarlo con @superberny70 al principio pensé que era normal ya que se escribían muchas líneas en el log, pero mirándomelo mejor, me di cuenta que el problema se debía al método para detectar el modulo/función desde el que se escribía en el log ya que este penalizaba mucho el rendimiento.
He modificado el método por otro que no penaliza tanto el rendimiento y se obtienen los mismos resultados.
> mejora rendimiento logger

- python/main-classic/channels/biblioteca.xml
- python/main-classic/core/library.py
En la nueva versión se puso, para intentar evitar problemas con ciertos caracteres, el uso del título localizado en las carpetas de la biblioteca.
Aunque estas carpetas en el uso habitual de un usuario deben de ser invisibles, en mi caso prefiero tener el título original (para cuando entro a ellas por algún motivo: compartir, toquetear cosas o lo que sea), como ocurría antes, por lo que he puesto una opción (que trabaja de la nueva forma por defecto) para poder usar el título localizado o bien el original.
> Posibilidad (configurable) de usar el título original en las carpetas de la biblioteca

- python/main-classic/platformcode/mct.py
En su día se habló de meter python_libtorrent dentro de lib para no tener
que depender de scripts externos, pero veo que todavía no está metida.
Supongo que la llamada a lib.python_libtorrent es un error por lo menos
hasta que se meta libtorrent dentro de lib.
Llamando a python_libtorrent provista por script.module.libtorrent funciona
como siempre
> Usar python_libtorrent global en vez de la de lib

- python/main-classic/core/library.py
A raiz de [este ](http://www.mimediacenter.info/foro/viewtopic.php?f=14&t=8202&hilit=+if+isinstance+item.extra%2C+str+%23%23%23+in+item.extra&p=37093#p37028)mensaje del foro y de la PR #496
> Bug al añadir series cuando item.extra no es un str

- python/main-classic/core/library.py
- python/main-classic/platformcode/platformtools.py
Parece q con la PR #500  fui demasiado radical, asi q lo he suavizado un poco como porponia @Palatosino en la #505.
Ahora, si en preferencias tenemos desactivado "Forzar modo de vista" el plugin se comportara como siempre (ignorando viewmode) y solo veremos los nuevos cambios con este parametro activado.
Como siempre teneis mas informacion en el foro: http://www.mimediacenter.info/foro/viewtopic.php?f=14&t=8340&p=37240#p37240
> Kodi, skins y vistas disponibles: viewcontent y viewmode (v2)

- python/main-classic/channels/configuracion.py
- python/main-classic/core/downloadtools.py
En el caso de que el archivo exista en lugar de sobrescribirlo añadía el nuevo contenido al final del archivo existente, para corregir eso se añade un nuevo parámetro a downloadtools.downloadfile para que en caso de existir el archivo y querer sobreescribirlo, se haga por completo en lugar de añadirse al final del archivo como ocurría. Por defecto se mantiene tal y como estaba y se resume el archivo si no se indica nada.
> Corregida función añadir/actualizar canales

- python/main-classic/library_service.py
En la última v4.2.0~beta2 la selección de versión de Kodi que hace con `monitor=xbmc.Monitor()` devuelve una función válida en Frodo (12.3), que luego falla en `monitor.abortRequested()`
Este otro método para seleccionar la versión parece más robusto:
`version_xbmc = int(xbmc.getInfoLabel("System.BuildVersion").split(".", 1)[0])`
> Arregla fallo de monitor.abortRequested() en Frodo

- python/main-classic/channels/hdfull.py
- python/main-classic/channels/hdfull.xml
- python/main-classic/core/httptools.py
Mientras intentaba reparar el canal hdfull que ahora utiliza cloudflare mediante la librería httptools (la cual me encanta, funciona genial y con scrapertools cloudflare suele fallarme), me he dado cuenta de que no terminaba de autorizar la url de cloudflare debido a que al no reemplazar las headers, se unían las headers por defecto y las del parámetro headers, dando error porque deben ser las mismas en todas las llamadas.
Pongo el log de ejemplo para que se vea más claro: http://pastebin.com/S78XFbwF
> Reparado hdfull y fallo de autorizacion cloudflare en httptools

- python/main-classic/platformcode/launcher.py
- python/main-classic/resources/settings.xml
Al hacer:
canal --> Buscar -[se abre teclado]-> introducir texto --> Darle a un resultado
Si ahora en este punto en Kodi 16 vamos hacia atrás salen los últimos resultados (al menos en la mayoría de dispositivos, hay quejas de que se produce lo que intenta evitar este PR también en Kodi 16 según el dispositivo) y si le das hacia atrás vas al main del canal. Si le vuelves a dar a buscar sale el teclado de nuevo.
En Kodi 17 se ha eliminado la cache, o eso parece, por lo que al darle hacia atrás aparece de nuevo el teclado, lo que es muy incómodo.
En este PR lo que hago es guardar la última búsqueda (independientemente del sistema de guardar última búsqueda que se muestra en el teclado). Se trackean los elementos retornados por las diferentes acciones en búsqueda de elementos con "item.action …
> Usar la última búsqueda para evitar la repetición de pregunta en Kodi 17

- python/main-classic/core/filetools.py
- python/main-classic/core/httptools.py
Se han corregido dos problemas de compatibilidad con Python 2.4:
1. El modulo samba no es compatible con Python 2.4 (hay que revisarlo) de modo que pongo el inport en filetools mediante un try para que por lo menos siga funcionando en local.
2. httptols, corregido el método para obtener el código de error en caso de no poder acceder a la pagina web, ya que al parecer este cambia en Python 2.4
> Compatibilidad

- python/version-mediaserver/core/config.py
Como se comento en #541 la versión mediaserver no funciona tras eliminar el archivo "versión.xml" ahora la he modificado, escribiendo los valores de versión y fecha directamente en el config.py
Mas adelante se decide si se mantiene asi o se usa otro método común para todas las plataformas.
> [mediaserver] - Cambios tras eliminar version.xml

- python/version-plex/Code/__init__.py
Como esta comentado en #549 en plex no se mostraban correctamente los caracteres con tildes ya que para plex hay que pasar los títulos en Unicode, el ítem tal como está echo ahora no permite usar otra codificación que no sea "UTF8" y se convierte automáticamente si se intenta usar otra, de ahí que en plex se hacia `item.title = unicode( item.title, "utf-8" , errors="replace" )` pero este se volvía a pasar a utf8 automáticamente, he modificado el __init__.py de plex para solucionar eso.
> [Plex] - Fix para mostrar caracteres con tildes en los titulos

- python/main-classic/platformcode/launcher.py
- python/main-classic/platformcode/platformtools.py
- python/version-mediaserver/platformcode/launcher.py
- python/version-plex/Code/__init__.py
Hasta ahora cuando un canal tenia la función play dentro del canal, esta función devolvía un itemlist, pero solo se utilizaba el primer ítem para pasarlo a reproducir, para canales que tienen la función play en el canal, pero el server del video no es "directo" el server ya se encarga de buscar las diferentes calidades para ese enlace si existen, pero cuando es un enlace directo al vídeo, no hay posibilidad de pasar varias urls para varias calidades si el canal los soporta, de modo que esta modificación lo que hace es:
- Si el primer resultado de la función play es un "ítem" sigue funcionando como siempre
- Si el primer resultado de la función play es un "list" lo añade al ítem como ítem.video_urls
- en platformtools si  el ítem tiene el parámetro video_urls coge estas en vez de pasar por …
> Permitir varias calidades cuando se ejecuta "play" desde canal

- python/main-classic/channels/descargas.py
Soluciona un fallo en descargas que daba error al comenzar la descarga en Windows según lo comentado en #555
> fix encoding en descargas

- python/main-classic/channels/animeflv_me.py
- python/main-classic/channels/animeflv_me.xml
Actualizado el canal Animeflv.me:
- Limpieza de código
- Arreglado un problema que hacia que al realizar búsquedas y estas devolvieran un solo resultado, se mostrara una lista vacía.
- Modificada la url de la opción Novedades de http://animeflv.me/ListadeAnime/LatestUpdate a http://animeflv.me/ListadeAnime/Nuevo.
- Se elimino una petición innecesaria para obtener las páginas de búsqueda por orden alfabético.
- Se paso a usar httptools.
- Soluciona el error al no encontrar vídeos debido a un cambio en el dominio (api.animeflv.me -> player.animeflv.me) que se realizo hace unas horas.
- Se agrego renumbertools al menú contextual en las búsquedas.
> Actualizado animeflv.me

- python/main-classic/channels/configuracion.py
- python/main-classic/platformcode/xbmc_config_menu.py
- Se añade un Try-Except en el canal configuración para evitar que si un XML está mal no se abra el canal
- Se corrige un fallo en la ventana de configuración de canales que no saltaba los controles deshabilitados al pasar de uno a otro con las flechas
> [Configuración] Fix ventana configuración + Fallo en XML

- python/main-classic/channels/hdfull.py
- python/main-classic/core/httptools.py
- python/main-classic/platformcode/platformtools.py
Tras lo comentado en #572, hago este PR con lo que seria una prueba sobre hdfull 
- Añadida función en httptools get_url_headers(url) que devuelve la url con los headers añadidos
- Añadidas dos líneas en render_items para que añada los headers a los thumbnail y los fanarts
- Modificado hdfull para probar que funcione correcto.
NOTA: Para que funcione correctamente con cloudflare, el canal debe usar los headers por defecto que trae httptools, por lo menos el user-agent.
Si la url de la imagen YA contiene los headers porque se los ha puesto el canal, la función de httptools ignora esa imagen y no modifica nada.
En las pruebas que he realizado parece funcionar correctamente, si alguien quiere probarlo sobre sus canales que usen cloudflare estaría bien.
> [httptools] Obtener automaticamente los headers para las imagenes alojadas en servidor con cloudflare

- python/main-classic/platformcode/launcher.py
- python/main-classic/resources/settings.xml
This reverts commit cd507e6cb1da750b70e173fa6ecf275501ab78e3.
Pull request #548
Como parece que recuperan la cache en Kodi 17 hago un revert de la funcionalidad, que además da algunos ligeros problemas en Kodis con cache (< 17).
Concretamente al darle hacia atrás, como no carga de nuevo los items, no se desactiva el elemento buscado. Es decir, da problemas en Kodi's con caches. Como parece que la han recuperado, lo revierto para que se comporte como siempre.
> Revert "Trackt itemlist elements for "search" action item"

- python/main-classic/channels/peliculasdk.py
- python/main-classic/channels/txibitsoft.py
- python/main-classic/channels/zentorrents.py
Hay canales (los que indico) que retornan un item de "No hay resultados".
Se pueden ver fácilmente buscando "slkfjs" (por ejemplo) y ahí los tendréis.
Simplemente he cambiado los canales para que no añadan ese elemento fake y se comporten como los demás: retornen listas vacías.
> Quitar elemento de "Sin resultados" en algunos canales

- python/main-classic/platformcode/platformtools.py
Ya que actualmente va simplemente a "get_data()" lo cual no me parece correcto. Debería estar en el downloads (o otro individual para los torrents) para poder llevarlo a otros sitios con más espacio (o donde nos de la gana).
Creo que el otro cliente interno (que me peta) ya usa este directorio.
> [libtorrent client] Usar el directorio de "downloads"

- python/version-plex/core/logger.py
El logger de la versión Kodi acepta llamar a sus métodos sin recibir ningún argumento, pero en plex es necesario pasarle uno, por lo que se producen errores.
> Fix logger en plex cuando no recibe texto

- python/main-classic/channels/cineasiaenlinea.py
- python/main-classic/channels/cineasiaenlinea.xml
- python/main-classic/channels/clasicofilm.py
- python/main-classic/channels/clasicofilm.xml
- python/main-classic/channels/divxatope.py
- python/main-classic/channels/novedades.py
- python/main-classic/channels/novedades.xml
- python/main-classic/core/item.py
- Añadido cauadro de progreso y trazas en el log como se pedia en #622 
- He aprovechado para añadir perfiles de color, ahora todos los items salen del mismo color.
- He mantenido el modo secuencial por q asi es mas facil localizar si algun canal da problemas y bloquea la busqueda, aunq si esta seleccionado este modo aparece un cuadro de dialogo avisando d q solo debemos usarlo para debugear e invitando a cambiarlo al modo concurrente.
- Un par de canales devolvian el item de "pagina siguiente" y he tenido q modificarlos.
- Aprovecho tb para incluir en Item un nuevo atributo reservado "contentQuality"
> [novedades] Añadir cuadro de progreso

- python/main-classic/core/logger.py
Atendiendo la peticion #589 (y lo hablado con @r0balo en la #627) he eliminado la comprobacion a la hora de escribir en el log en caso de error: logger.error() ahora siempre esta activado.
Ademas ahora lo escribe como un ERROR y no como una NOTICE como hasta ahora.
Por supuesto hay q usarlo para lo q realmente es, para indicar errores y no trazas (q serian los logger.info()) o para depurar (q serian los logger.debug()). Y si puntualmente queremos usarlo como un simple print, deberemos prestar atencion para eliminarlos cuando terminemos la depuracion.
Esta probado en Xbmc v10 (Dharma), kodi v16 y kodi v17.
En la version mediaserver ya estaba implementado asi. En las versiones plex y command-line ya se escribia siempre cualquier funcion del logger (no habia q activar nada).
> [FIX #589] logger.error

- python/version-mediaserver/platformcode/template/css/pelisalacarta.css
- python/version-mediaserver/platformcode/template/js/protocol.js
- python/version-mediaserver/platformcode/template/js/ui.js
- python/version-mediaserver/platformcode/template/page.html
- Se corrige un fallo al hacer platformtools_itemlist_refresh() que producía un bucle infinito.
- Se oculta el panel de información izquierdo cuando la pantalla no es suficientemente ancha (<800px) mas que nada para dispositivos móviles con el uso veremos si este valor (800) conviene ampliarlo o reducirlo... pero creo que así esta bastante bien...
> [mediaserver] - Mejoras

- python/main-classic/channels/biblioteca.xml
- python/main-classic/library_service.py
Se han pasado todos los ajustes que quedaban pendientes de ocultos a desactivados.
Se ha modificado library_service para q ahora el retraso "updatelibrary_wait" se ejecute dentro del main, por lo q afectara a la conversion de la bilbioteca y al arranque del monitor tb.
> [Fix #661] Continuacion de #663

- python/main-classic/core/library.py
- python/main-classic/platformcode/launcher.py
- python/main-classic/platformcode/platformtools.py
- python/main-classic/platformcode/xbmc_info_window.py
Corregido problema que comentaba un usuario en :
http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=8527&start=250#p40465
- Se ha puesto un try except en dialog_progress_bg que en caso de fallo muestra un dialog_progress porque en versiones antiguas el primero no esta disponible
- Se usan números absolutos para los ID de las acciones en info_window porque en versiones antiguas las constantes definidas en xbmcgui no existen
- Se limita la cantidad de información en el .strm (para películas) ya que .strm mas grande de 1kb no se cargan en versiones antiguas
- Modificado el sistema para "engañar" a xbmc al reproducir un strm (antes se intentaba reproducir un archivo de imagen para que xbmc se callara) pero en versiones antiguas muestra un mensaje de error, así que modifico la ruta para …
> fix biblioteca xbmc 12

- python/main-classic/core/httptools.py
En ocasiones, cuando se producía un error al obtener la página, en vez de devolver el error, se producía una excepción que detenía el proceso.
> fix httptools error handling

- python/main-classic/channels/configuracion.py
- python/main-classic/channelselector.py
- python/main-classic/core/channeltools.py
- python/main-classic/core/item.py
- python/main-classic/platformcode/launcher.py
- python/main-classic/platformcode/platformtools.py
Añadida opción para permitir configurar canales desde el menú contextual (Atajo) y no tener que ir a la parte de configuración del addon.
Gracias a @superberny70 por la sugerencia.
> Mostrar "configurar canal" en el menú contextual #617, Fix búsqueda, Fix Información, atajos para opciones menu principal

- python/main-classic/core/config.py
- python/main-classic/platformcode/xbmc_library.py
- python/main-classic/resources/settings.xml
Disculpar pero se me habia quedado un commit sin enviar...
- cambio de nombre establecer_contenido por set_content
- Añadida opcion en Preferencias - Rutas para deshabilitar el autoconfigurador de la biblioteca (para casos especiales)
- Ahora el autoconfigurador tambien funciona con rutas samba
> Continuacion de #669

- python/main-classic/channelselector.py
Ocultar la categoria Adulto si no esta activado este modo en las preferencias, que desde la #668 se mostraba cuando no tocaba..
> Modo adultos en channelselector

- python/main-classic/channels/descargasmix.py
- python/main-classic/channels/descargasmix.xml
- python/main-classic/servers/gamovideo.py
- python/main-classic/servers/gamovideo.xml
- Descargasmix: cambios en el proxy que usa para versiones no compatibles con https
- Gamovideo: actualizado user-agent ya que falla con el que trae por defecto httptools
> Reparado descargasmix y gamovideo

- python/build.xml
- python/main-classic/core/config.py
Se realiza en cada inicio junto con la comprobación de carpetas predefinidas del addon. Se consulta la carpeta por defecto que indique el skin activo y si no existe o los archivos en su interior no concuerdan con la carpeta 720p, se crea/copian.
Comentado en el foro: http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=12234&p=46493#p46474
> Comprobacion y creación de carpetas para los xml según el skin

- python/main-classic/servers/clicknupload.py
- python/main-classic/servers/clicknupload.xml
- python/main-classic/servers/documentary.xml
- python/main-classic/servers/kingvid.xml
- python/main-classic/servers/letwatch.xml
- python/main-classic/servers/mediafire.py
- python/main-classic/servers/mediafire.xml
- python/main-classic/servers/mp4upload.xml
- python/main-classic/servers/raptu.py
- python/main-classic/servers/raptu.xml
- python/main-classic/servers/thevideome.py
- python/main-classic/servers/tunepk.xml
- python/main-classic/servers/turbobit.xml
- python/main-classic/servers/turbovideos.xml
- python/main-classic/servers/tutv.xml
- python/main-classic/servers/userscloud.py
- python/main-classic/servers/userscloud.xml
- python/main-classic/servers/vidabc.xml
- python/main-classic/servers/vidzi.py
- python/main-classic/servers/zippyshare.py
- Reparados: Mediafire, zippyshare, clicknupload (usa proxy en caso de fallo por https), thevideome y userscloud.
- Raptu solo funciona en Kodi 17 ya que la url del vídeo está ligada a la ip y no es posible usar proxy.
> Reparados varios conectores y expresiones regulares en los xml

- python/main-classic/platformcode/platformtools.py
- python/main-classic/servers/auroravid.xml
- python/main-classic/servers/datoporn.xml
- python/main-classic/servers/netutv.xml
- python/main-classic/servers/rapidvideo.py
- python/main-classic/servers/rapidvideo.xml
- python/main-classic/servers/raptu.py
- python/main-classic/servers/tusfiles.py
- python/main-classic/servers/tusfiles.xml
- python/main-classic/servers/watchers.py
- Reparado watchers
- Añadido servidor tusfiles.net a tusfiles (discriminando para no confundir con tusfiles.org)
- Regex de auroravid, datoporn, netutv, rapidvideo.
- Raptu y rapidvideo muestran aviso de que no funcionan por debajo de Kodi 17 debido a https
Opción buscar trailer en platformtools: Se cambia de lugar para que se añada al menu cuando el action es findvideos, antes solo se hacia si el item.context era str.
> Corregidos algunos conectores pendientes

- python/main-classic/channels/animeflv.py
- python/main-classic/channels/biblioteca.py
- python/main-classic/channels/configuracion.py
- python/main-classic/core/library.py
- python/main-classic/library_service.py
Revisada velocidad en lo referente a obtener archivos, carpetas de la biblioteca, tanto para películas como series.
Como se sabe la estructura de datos, no hace falta usar el método walk, de hecho no hace falta búsqueda recursiva, solo listados de un directorio o subdirectorio, por lo que se ha mejorado bastante el tiempo de obtención de estos datos.
Corrección en el listado de episodios para algunos casos.
> Fix #801, fix animeflv lista episodios
