- python/main-classic/channels/seriesblanco.py
Se arregla en el titulo del capitulo que salgan todos los idiomas disponibles.
-ANTES
The Flash - 1x01 Capitulo 01 [Español]
-DESPUES
The Flash - 1x01 Capitulo 01 [Español][Latino][VOS]
> Fix idiomas en la descripcion del capitulo

- python/main-classic/channels/zentorrents.py
- python/main-classic/channels/zentorrents.xml
Se modifica la forma de atrapar la url en findvideos. Se corrige código
info para series y películas. Se elimina parte de código erróneo y
parte ya inservible.
> Corrección cambios web

- python/main-classic/library_service.py
- python/main-classic/platformcode/launcher.py
- python/main-classic/resources/settings.conf
- python/main-classic/resources/settings.xml
version avanzada sugerida por Jesús
> Filtrado de servidores

- python/main-classic/channels/beeg.py
- python/main-classic/channels/beeg.xml
Corregido el canal Beeg para usar la API dela página
> Canal Beeg corregido

- python/main-classic/platformcode/xbmctools.py
Mas info en: http://www.mimediacenter.info/foro/viewtopic.php?f=14&p=27328&sid=a9b50261ac45b0db5dcb181c9e96ccb7#p27328
> Implementada funcionalidad para añadir infoLabels a xbmcgui.ListItem.

- python/main-classic/channels/pepecine.py
- python/main-classic/channels/pepecine.xml
Mas info en: http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=7093
Añadir al chanelselector:
itemlist.append( Item( title="Pepecine", channel="pepecine", language="ES", category="F,S", type="generic", thumbnail="https://d12.usercdn.com/i/02278/nwm6todp6yyk.png"))
Recomendable aplicar antes las Pull Request #37 y #52
> Añadido nuevo canal pepecine

- python/main-classic/servers/vimpleru.py
url + cookie.
En mi versión no estaba incluido el conector en servertools, estaba comentado.
> Update conector vimpleru.py

- python/main-classic/platformcode/xbmctools.py
arreglo de %s por .format() para que no de error en `animeflv` y se carga los servidores de "episodios recientes"
> fix para animeflv

- python/main-classic/channels/bityouth.py
- python/main-classic/channels/bityouth.xml
- python/main-classic/channels/peliculasdk.py
- python/main-classic/channels/peliculasdk.xml
- python/main-classic/channels/txibitsoft.py
- python/main-classic/channels/zentorrents.py
- python/main-classic/channels/zentorrents.xml
Añadida api arts, info scroll , info label y correcciones por cambios
en web
> Bityouth,Peliculasdk,Txibitsoft yZentorrent update

- python/main-classic/channels/peliserie.py
- Corregido Bug en Buscar... y Series al coger los capitulos
- Añadido Fanart en peliculas mediante el scraper tmdb.py.
- Añadidas las sinopsis en series y peliculas.
- Aconsejable Forzar Vista en la configuracion de pelisalacarta.
Teneis el thumbnail en: http://i.imgur.com/KfFpe4l.png
No he añadido el xml por q no se realmente cual es el formato correcto para la version 4.0.x
> hotfix peliseries

- python/main-classic/channels/seriecanal.py
- python/main-classic/channels/seriecanal.xml
Comentado en el foro: http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=7113
Añadido xml del canal con el nuevo formato
> Nuevo canal seriecanal

- python/main-classic/servers/openload.py
Modificado con los últimos cambios a partir del conector creado por DrZ3r0
Dejo el servertools.py sin tocar porque no sé si está pendiente de cambio a raíz del arreglo de vimpleru por r0balo en el pull request https://github.com/tvalacarta/pelisalacarta/pull/51
> Nuevo conector openload

- python/main-classic/channels/mejortorrent.py
Me he dado cuenta de que algunos títulos no se mostraban correctamente porque el patrón se los saltaba.
> Arreglo de errores en patrones de mejortorrent

- python/main-classic/core/tmdb.py
cambios en la version 1.3:
- Corregido error al devolver None el path_poster y el backdrop_path
- Corregido error que hacia que en el listado de generos se fueran acumulando de una llamada a otra
- Añadido metodo get_generos()
- Añadido parametros opcional idioma_alternativo al metodo get_sinopsis()
mas info: http://www.mimediacenter.info/foro/viewtopic.php?f=14&t=7059
> Hot fix tmdb

- python/main-classic/channels/jkanime.py
- python/main-classic/channels/jkanime.xml
- python/main-classic/servers/openload.py
Reparado error que impedía listar episodios, arreglados thumbnails y el patrón para videos alojados en jkanime. Eliminada función play al no ser ya necesaria.
Comentado en el foro: http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=7104
> Fix jkanime

- python/main-classic/channels/jkanime.py
- python/main-classic/channels/jkanime.xml
- python/main-classic/channels/seriecanal.py
- python/main-classic/channels/seriecanal.xml
- python/main-classic/servers/openload.py
Corregidos errores en el código del scraper tmdb
> Fix seriecanal

- python/main-classic/channels/bityouth.py
- python/main-classic/channels/bityouth.xml
- python/main-classic/channels/bricocine.py
- python/main-classic/channels/bricocine.xml
En esta actualización he añadido mejoras en la velocidad de obtención
de info episodios en series, ademas de multi-fanart, que no es más que
ahora en cada peli o serie tenderemos diferentes fanarts según donde
nos coloquemos. También he añadido televisiontunes en series ; cuando
entremos en una serie, si la tiene, sonará la "musiquita" de la misma.
Y , con esto ultimo he añadido una opción que , en muchas ocasiones me
ha jo**** tela, tela , que es el no refrescar cuando navegamos hacia
atrás en el addon. Con este propósito he creado con la gran e
inestimable ayuda de Robalo, el force-refresh. Cansados de dar vueltas
y no encontrar ninguna posibilidad de forzar a Kodi el refresco cuando
navega hacia atrás, la una via que vi, fue pasar por encima del mismo.
Básicamente lo que hace , …
> Bricocine, Bityouth Update

- python/main-classic/channels/bityouth.py
- python/main-classic/channels/bityouth.xml
- python/main-classic/channels/bricocine.py
- python/main-classic/channels/bricocine.xml
Correción en la obtención de tul torrent en Bityouth  y varios cambios
en themovier.org  en ambos
> Fix Bricocine y Bityouth

- python/main-classic/channels/peliculasdk.py
- python/main-classic/channels/peliculasdk.xml
- python/main-classic/channels/repelis.py
- python/main-classic/channels/repelis.xml
- python/main-classic/channels/txibitsoft.py
- python/main-classic/channels/txibitsoft.xml
- python/main-classic/channels/zentorrents.py
- python/main-classic/channels/zentorrents.xml
- python/main-classic/servers/netutv.py
> Txbisoft , PeliculasDK Update

- python/main-classic/channels/newpct.json
- python/main-classic/channels/newpct.py
- python/main-classic/channels/newpct.xml
- python/main-classic/channels/pordede.json
- python/main-classic/channels/pordede.py
- python/main-classic/channels/pordede.xml
- python/main-classic/channels/seriesyonkis.json
- python/main-classic/channels/seriesyonkis.py
- python/main-classic/channels/seriesyonkis.xml
- python/main-classic/channels/xhamster.json
- python/main-classic/channels/xhamster.py
- python/main-classic/channels/xhamster.xml
-Newpct: Correcciones, reestructuración de los menús y ahora dentro de cada serie muestra los capítulos de todas las temporadas. http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=7116&p=27868#p27863
-Pordede: Corregida la paginación. http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=7177&p=28038#p28038
-Seriesyonkis: Corregidos errores en función addChapters y findvideos. http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=7049&p=27083#p27083
-Xhamster: Canal prácticamente rehecho por cambios en la web.
> Update newpct, pordede, seriesyonkis y xhamster

- python/main-classic/channels/inkapelis.json
- python/main-classic/channels/inkapelis.py
- python/main-classic/channels/inkapelis.xml
- python/main-classic/channels/pelisxporno.json
- python/main-classic/channels/pelisxporno.py
- python/main-classic/channels/pelisxporno.xml
Como reza el título, 2 nuevos canales, inkapelis con películas en castellano, latino y vos, y pelisxporno de contenido adulto (únicamente a través de openload).
> Añadidos canales inkapelis y pelisxporno

- python/main-classic/channels/divxatope.json
- python/main-classic/channels/divxatope.py
- python/main-classic/channels/divxatope.xml
- python/main-classic/servers/openload.py
Corregida expresión regular para los torrents en divxatope
> Fix divxatope y openload

- python/main-classic/channels/bricocine.py
Se repara reproducción películas. Muchas mejoras en código fanart.
Todas las películas y series estan ahora en torrent y con opción
magnet.
> Bricocine Update

- python/main-classic/channels/animeflv.json
- python/main-classic/channels/animeflv.py
- python/main-classic/channels/animeflv.xml
- Se elimina la referencia a requests, queda pendiente que se mejore scrapertools
- añadido metodo para evitar cloudflare, gracias a DrZ3r0
> Fix #92 referencia a requests y mejora cloudflare

- python/main-classic/channels/newpct1.json
- python/main-classic/channels/newpct1.py
- python/main-classic/channels/newpct1.xml
- python/main-classic/channels/pepecine.json
- python/main-classic/channels/pepecine.py
- python/main-classic/channels/pepecine.xml
Pepecine: Corregido el idioma en la seccion Ultimos Capitulos.
Newpct1: Añadido servidor en los titulos de los enlaces de descarga.
> hotfix pepecine y newpct1

- python/main-classic/servers/torrent.py
> Add quasar as torrent player

- python/main-classic/channels/allpeliculas.json
- python/main-classic/channels/allpeliculas.py
- python/main-classic/channels/allpeliculas.xml
- python/main-classic/channels/descargasmix.json
- python/main-classic/channels/descargasmix.py
- python/main-classic/channels/descargasmix.xml
DescargasMIX (mil gracias a SeiTaN y robalo): http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=7277
Allpeliculas: http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=7286
> Nuevos canales

- python/main-classic/channels/pordede.json
- python/main-classic/channels/pordede.py
- python/main-classic/channels/pordede.xml
- python/main-classic/servers/cnubis.py
Corregido pordede por pequeños cambios en la web al listar contenido y extraer la url de los vídeos: http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=7299#p29013
En cnubis modificada la url de acceso (https por http) a raíz de errores reportados en el foro: http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=7224
Añadido en pordede fanart y ventana info/sinopsis gracias a super_berny:
http://www.mimediacenter.info/foro/viewtopic.php?f=22&p=29051#p29030
> Fix pordede y cnubis

- python/main-classic/channels/pelismagnet.py
> Incluid pelismag.net

- python/main-classic/channels/pelismagnet.xml
> Incluid pelismag.net (2)

- python/main-classic/servers/openload.py
Modificada la url del vídeo que devuelve por una más directa ya que la
actual se queda trabada en muchas ocasiones, junto con el header
necesario para posibilitar su descarga. Ahora también discrimina si el
enlace contiene vídeo o no, y en este segundo caso extrae la dirección
de descarga del archivo.
> Cambios en openload

- python/main-classic/servers/servertools.py
Este pequeño cambio no fue incluído, por error, en el pull request anterior y por esa razón no es reconocido el server como premium.
> Cambio imprescindible para que filesmonster sea considerado como server premium

- python/main-classic/core/tmdb.py
Reemplazada api_key, la anterior habia dejado de funcionar
> Corregido bug en tmdb.py

- python/main-classic/channels/documaniatv.py
- python/main-classic/channels/documaniatv.xml
Actualizado por cambios en la web. Arreglado menú por categorías.
> Fix documaniatv

- python/main-classic/servers/flashx.py
Modificada la url de acceso al vídeo por una embebida para que ya no sea necesario esperar 5 segundos y cargar una segunda vez la página.
> Mejoras en conector flashx

- python/main-classic/servers/servertools.py
- python/main-classic/servers/thevideos.py
- python/main-classic/servers/videowood.py
-Conector para videowood.tv creado por **DrZ3r0** para el addon streamondemand y modificado para hacerlo compatible con pelisalacarta. (se usa en los canales mocosoftx y pelisxporno)
-Conector para thevideos.tv (se usa en el canal allpeliculas)
-Modificado servertools para añadir ambos.
> Nuevos conectores: videowood y thevideos

- python/main-classic/servers/servertools.py
Unificado el buscador de los dos proveedores del canal Filesmonster Catalogue
> Mejoras en el canal filesmonster catalogue (unificado buscador)

- python/main-classic/channels/hdfull.py
- python/main-classic/channels/hdfull.xml
Cambios en hdfull para que muestre solo los servidores que tienen conector y se oculten los premium si está marcada esa opción, así se evita mostrar items que no tienen utilidad y que hacen la lista innecesariamente larga.
> Modificado hdfull

- python/main-classic/channels/aquitorrent.py
- python/main-classic/channels/aquitorrent.xml
- python/main-classic/channels/bityouth.py
- python/main-classic/channels/bityouth.xml
- python/main-classic/channels/bricocine.py
- python/main-classic/channels/bricocine.xml
- python/main-classic/channels/multicineonline.py
- python/main-classic/channels/multicineonline.xml
- python/main-classic/channels/peliculasdk.py
- python/main-classic/channels/peliculasdk.xml
- python/main-classic/channels/teledocumentales.py
- python/main-classic/channels/teledocumentales.xml
- python/main-classic/channels/txibitsoft.py
- python/main-classic/channels/txibitsoft.xml
- python/main-classic/channels/verseriesonlinetv.py
- python/main-classic/channels/verseriesonlinetv.xml
- python/main-classic/channels/zentorrents.py
- python/main-classic/channels/zentorrents.xml
- python/main-classic/servers/idowatch.py
- python/main-classic/servers/vk.py
Aquitorrent ,bityouth,bricocine— Cambios web y mejoras fanrt —
> Actualizaciones y nuevo canal

- python/main-classic/servers/openload.py
Mejoras en la función decode gracias a robalo :+1:
> Mejoras en openload

- python/main-classic/servers/allvid.py
- python/main-classic/servers/clicknupload.py
- python/main-classic/servers/idowatch.py
- python/main-classic/servers/letwatch.py
- python/main-classic/servers/lolabits.py
- python/main-classic/servers/servertools.py
- python/main-classic/servers/streamcloud.py
- python/main-classic/servers/streame.py
- python/main-classic/servers/streamplay.py
- python/main-classic/servers/uptobox.py
- python/main-classic/servers/vidgg.py
- python/main-classic/servers/vodbeast.py
- python/main-classic/servers/youwatch.py
-Modificado  streamcloud para que no sea necesario esperar 10 segundos
para sacar la url del vídeo.
-Corregido uptobox casi al completo, se añade como servidor free.  Tanto
para archivos en streaming como para descarga (se puede probar en el
canal cinehanwer)
-Añadido lolabits como servidor free, también válido para archivos
alojados en abelhas.pt  (se puede probar en cinehanwer)
-Añadidos en servertools uptobox y lolabits.
**Nuevos cambios (25/02):**
-Corregidos idowatch, youwatch y letwatch.
-Añadidos streame, streamplay, vidgg, vodbeast, allvid y clicknupload (todos ellos se pueden probar en hdfull)
-Modificado servertools con los nuevos conectores.
> Mejoras y nuevo conector (streamcloud, uptobox, lolabits)

- python/main-classic/channels/descargasmix.py
- python/main-classic/channels/descargasmix.xml
Reparado por cambios en la web en los enlaces online junto con cambios menores en el código.
> Reparado descargasmix

- python/main-classic/servers/moviecloudto.py
Lentorro algunas veces, pero no deja de ser una opción más por si acaso. (Visto en hdfull)
> Nuevo conector moviecloudto

- python/main-classic/servers/cnubis.py
- python/main-classic/servers/flashx.py
- python/main-classic/servers/gamovideo.py
- python/main-classic/servers/openload.py
- python/main-classic/servers/realdebrid.py
- python/main-classic/servers/servertools.py
- python/main-classic/servers/uploadedto.py
- python/main-classic/servers/uptobox.py
- Reparado cnubis por cambios en la url de los vídeos.
- Corregidos gamovideo, flashx y realdebrid.
- Modificado servertools para añadir openload, clicknupload y youwatch como servidores para real-debrid.
- Cambios en uptobox: Ahora uptostream tiene límite diario de 120 minutos (antes no funcionaba correctamente), así que si se ha alcanzado el límite intenta la descarga directa por uptobox.
- Reparado (otra vez xD) openload, gracias robalo por tu gran ayuda :wink: 
- Cambios en uploadedto en la función find_videos, si la dirección apunta a una carpeta, lista y devuelve los enlaces que haya dentro. Resumido el patron en uno solo.
> Conectores corregidos (cnubis, openload, gamovideo, flashx)

- python/main-classic/channels/seriesblanco.json
- python/main-classic/channels/seriesblanco.py
- python/main-classic/channels/seriesblanco.xml
- python/main-classic/platformcode/library.py
He arreglado el listado de seriesblanco y simplificado muchísimo el código de la obtención de enlaces (siendo más rápido)
> Fix seriesblanco

- python/main-classic/channels/cultmoviez.py
- python/main-classic/channels/cultmoviez.xml
- python/main-classic/channels/verseriesynovelas.py
- python/main-classic/channels/verseriesynovelas.xml
- python/main-classic/platformcode/xbmctools.py
- Canal cultmoviez modificado utilizando como base el creado por robalo, se le añade la reproducción con subtítulos y otros cambios menores.
- Modificado xbmctools para la carga de subtítulos.
- Nuevo canal de la web www.verseriesynovelas.tv
> Nuevos canales, cultmoviez y verseriesynovelas

- python/main-classic/channels/animeflv.py
- python/main-classic/channels/animeflv.xml
Se actualiza la ruta para centralizar los ficheros de configuración (desarrollo de super_berny)
> update en ruta de la carpeta

- python/main-classic/channels/descargacineclasico.py
- python/main-classic/channels/descargacineclasico.xml
- python/main-classic/servers/sh.py
Hola adjunto el canal descargacineclasico.net para su inclusión en la nueva version si lo creeis conveniente.
Un Saludo
> Nuevo canal:descargacineclasico.me

- python/main-classic/servers/bigfile.py
- python/main-classic/servers/rapidgator.py
- python/main-classic/servers/servertools.py
- python/main-classic/servers/uploadable.py
A raíz de de este tema en el foro y con la ayuda de robalo e ivan_kodi:
- Se modifican los patrones de rapidgator y uploadable.
- Se añade el conector bigfile.
- Se modifica servertools para incluir a uploadable y bigfile como servidores para real-debrid.
> Cambios en conectores

- python/main-classic/platformcode/launcher.py
- python/main-classic/platformcode/library.py
Con esto deberían estar corregidos los conflictos que comentaste @tvalacarta
> Corrección de conflictos

- python/main-classic/channels/aquitorrent.py
- python/main-classic/channels/aquitorrent.xml
- python/main-classic/channels/bityouth.py
- python/main-classic/channels/bityouth.xml
- python/main-classic/channels/bricocine.py
- python/main-classic/channels/bricocine.xml
- python/main-classic/channels/verseriesonlinetv.py
- python/main-classic/channels/verseriesonlinetv.xml
Bricocine, Bityouth, Aquitorrent y Verseriesonlinetv
> Mejoras código varios canales

- python/main-classic/channels/pelispedia.py
- python/main-classic/channels/pelispedia.xml
> pelispedia.py

- python/main-classic/servers/servertools.py
- python/main-classic/servers/zippyshare.py
El conector lleva tiempo sin funcionar.
Lo actualice (removieron el captcha) y agregue el código necesario para detectar si un enlace es funcional.
Primera vez que aporto a un proyecto y no estoy bien familiarizado con el código de pelisalacarta, así que disculpas de antemano si me pase algo por alto.
> Arreglado zippyshare y agregado como servidor gratuito

- python/main-classic/channelselector.py
- python/main-classic/core/item.py
- python/main-classic/core/jsontools.py
- python/main-classic/platformcode/launcher.py
- python/main-classic/platformcode/xbmctools.py
**xbmctools.py**:
* Obtener el itemurl desde la función del Ítem ítem.tourl() 
* Pasar el ítem en lugar de los parámetros sueltos a las funciones: **addnewfolderextra**,  **addnewvideo** y **play_video**
**launcher.py**
* Obtener el Ítem a partir de la función ítem.fromurl()
* Mantener el sistema anterior para poder abrir urls en el formato anterior mientras existan(principalmente STRM)
**cahnnelselector.py**
* Eliminar el código especifico de kodi y duplicado en el xbmctools para las funciones: **mainlist**, **channeltypes** y **listchannels**
Pequeños cambios en ítem.py y jsontools.py para solucionar el problema expuesto aquí: #119
>  Modificación para mejorar la correcta propagación del Item

- python/main-classic/channels/allpeliculas.py
- python/main-classic/channels/allpeliculas.xml
- python/main-classic/channels/descargasmix.py
- python/main-classic/channels/descargasmix.xml
- python/main-classic/channels/documaniatv.py
- python/main-classic/channels/documaniatv.xml
- python/main-classic/channels/inkapelis.xml
- python/main-classic/channels/tvvip.py
- python/main-classic/channels/tvvip.xml
- python/main-classic/channels/verseriesynovelas.py
- python/main-classic/channels/verseriesynovelas.xml
- python/main-classic/servers/allvid.py
- python/main-classic/servers/netutv.py
- python/main-classic/servers/uptobox.py
- python/main-classic/servers/vidbull.py
- Reparados **allvid** y **vidbull** por cambios en la web. **Uptobox/uptostream** vuelve a utilizarse como antes porque han quitado el límite diario. Cambios en los patrones de **netutv**.
- Reparado **verseriesynovelas** por utilizar ahora cloudflare. Tanto en este canal como en **allpeliculas** se añade soporte para la biblioteca y se corrige la función búsqueda.
- Reparado **tvvip** por numerosos cambios en la web.
- Reparada la función búsqueda en **documaniatv**.
- Reparado **descargasmix** ya que fallaba en la opción series y se añade soporte para la biblioteca.
> Mantenimiento de servidores y canales

- python/main-classic/channels/tvvip.py
Pequeña corrección para que funcionen en Plex algunas urls de los vídeos que contienen acentos.
> Corregido tv-vip por un error en Plex

- python/main-classic/platformcode/launcher.py
- python/main-classic/platformcode/xbmctools.py
He modificado la función:
xbmctools.renderItems(itemlist, params, item.url, item.category)
a:
xbmctools.renderItems(itemlist, item)
Pasamos el ítem en vez de los parametros
> Modificado xbmctools.renderItems

- python/main-classic/platformcode/xbmctools.py
se arregla problemas con subtitulos, incluye correcion #191 y se elimina codigo referente a cuevana, cuyo canal ya no existe.
> fix subtitulos en 4.0.8

- python/main-classic/channels/ayuda.py
- python/main-classic/library_service.py
- arreglado el canal ayuda.
- borrados imports no usados en library_service.
- queda pendiente cambiar la llamada a savelibrary de la biblioteca para usar el nuevo sistema de item.
> Fix al entrar en ayuda 4.0.8

- python/version-mediaserver/platformcode/launcher.py
- python/version-mediaserver/platformcode/template/js/popups.js
Este PR hay que mergearlo junto con el #196 
Modifica el launcher de la versión mediaserver para usar el nuevo updater.py que he publicado en #196
> Fallo updater en version mediaserver

- python/main-classic/servers/cnubis.py
Corregido el patrón por cambios en la url de los vídeos.
> Corregido cnubis

- python/main-classic/channelselector.py
se usa funcion dict.get() con valor por defecto
> optimizando código

- python/main-classic/lib/btserver/client.py
- python/main-classic/lib/btserver/dispatcher.py
- python/main-classic/lib/btserver/monitor.py
- python/main-classic/lib/megaserver/client.py
- python/main-classic/lib/megaserver/cursor.py
- python/main-classic/lib/megaserver/file.py
- python/main-classic/lib/megaserver/handler.py
- python/main-classic/servers/mega.py
- python/main-classic/servers/torrent.py
- python/version-mediaserver/platformcode/controllers/html.py
He hecho unas modificaciones es los servers torrent y mega para que funcionen en mediaserver
También he corregido algún problema en la versión mediaserver, y pequeñas modificaciones en servidor mega.
> [mediaserver] - modificacion de torrent y mega para funcionar en mediaserver mas alguna correccion

- python/main-classic/platformcode/xbmctools.py
Corregido error en la opción añadir a la biblioteca del diálogo de selección.
> Error en opción añadir a la biblioteca

- python/main-classic/channels/documaniatv.py
- python/main-classic/lib/aadecode.py
- python/main-classic/servers/dailymotion.py
- python/main-classic/servers/flashx.py
- python/main-classic/servers/gamovideo.py
- python/main-classic/servers/mailru.py
- python/main-classic/servers/openload.py
- python/main-classic/servers/pcloud.py
- python/main-classic/servers/playwire.py
- python/main-classic/servers/powvideo.py
- python/main-classic/servers/rutube.py
- python/main-classic/servers/servertools.py
- python/main-classic/servers/speedvideo.py
- python/main-classic/servers/uptobox.py
- python/main-classic/servers/videowood.py
- Reparado videowood. **Todo el mérito y las gracias a robalo** :smiley: 
- Refinado el código de openload utilizando el método modificado de videowood.
- En mailru y rutube, añadidos nuevos patrones de reconocimiento y cambios en el código para que se devuelvan varios enlaces según la calidad del vídeo.
- Nuevo conector para playwire.
- Corregido pequeño error en documaniatv, faltaba un import.
_**Nuevos cambios**_
- Exportado el método de openload y videowood a una librería externa para cubrir las diferentes variantes que utilizan esos servidores. Gracias robalo!
- Corregidos flashx (cambio en la url embebida), speedvideo y dailymotion (añadido también detección de subtítulos).
- Reparado gamovideo gracias a robalo. Añadida la opción para reproducir por rtmp.
- Nuevo conector para la …
> Nuevos conectores (playwire, pcloud) y mantenimiento (videowood, openload, mailru, flashx, uptobox...)

- python/main-classic/channels/areadocumental.py
- python/main-classic/channels/areadocumental.xml
Comentado en el foro: http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=7492
> Nuevo canal Area-Documental

- python/main-classic/core/item.py
Se corrige un pequeño error en ítem.py
> corregido item.py

- python/main-classic/lib/samba/libsmb.py
- python/main-classic/lib/samba/pyasn1/codec/ber/decoder.py
- python/main-classic/lib/samba/pyasn1/codec/ber/encoder.py
- python/main-classic/lib/samba/pyasn1/codec/ber/eoo.py
- python/main-classic/lib/samba/pyasn1/codec/cer/decoder.py
- python/main-classic/lib/samba/pyasn1/codec/cer/encoder.py
- python/main-classic/lib/samba/pyasn1/codec/der/decoder.py
- python/main-classic/lib/samba/pyasn1/codec/der/encoder.py
- python/main-classic/lib/samba/pyasn1/debug.py
- python/main-classic/lib/samba/pyasn1/type/base.py
- python/main-classic/lib/samba/pyasn1/type/char.py
- python/main-classic/lib/samba/pyasn1/type/constraint.py
- python/main-classic/lib/samba/pyasn1/type/error.py
- python/main-classic/lib/samba/pyasn1/type/namedtype.py
- python/main-classic/lib/samba/pyasn1/type/namedval.py
- python/main-classic/lib/samba/pyasn1/type/tag.py
- python/main-classic/lib/samba/pyasn1/type/tagmap.py
- python/main-classic/lib/samba/pyasn1/type/univ.py
- python/main-classic/lib/samba/pyasn1/type/useful.py
- python/main-classic/lib/samba/smb/base.py
- python/main-classic/lib/samba/smb/securityblob.py
- python/main-classic/library_service.py
- python/main-classic/platformcode/library.py
Corregidos imports y añadida la compatibilidad para samba en library_service.
> Compatibilidad con samba

- python/main-classic/servers/dailymotion.py
- python/main-classic/servers/nosvideo.py
- python/main-classic/servers/openload.py
- python/main-classic/servers/streaminto.py
- python/main-classic/servers/vk.py
- python/main-classic/servers/youwatch.py
- Reparados openload y vk, y añadido a streaminto la opción de reproducir por rtmp, gracias a @r0balo 
- Corregidos dailymotion, youwatch y nosvideo.
> Mantenimiento de conectores

- python/main-classic/channels/pepecine.py
- python/main-classic/channels/pepecine.xml
- python/main-classic/channels/pordede.py
- python/main-classic/channels/pordede.xml
Pordede: 
- Corregido bug al fijar sortlinks y showlinks 
- Reparada la opcion de añadir peliculas a la biblioteca
Pepecine:
- Reparada la opcion de añadir serie a la biblioteca desde el listado de episodios
> Correcciones varias en pordede y pepecine

- python/main-classic/platformcode/launcher.py
Modificado el launcher.py para detectar los ítem tipo TAG comprobando que el action no contenga nada, y no con un try-except como estaba, ya que esto detecta como TAGS todos los ítems que den error al ejecutarlos, y además no mostraba ningún error en el log, cosa que complica bastante detectar donde esta el problema en caso de producirse un error en el canal.
De esta manera si un ítem no contiene action, sencillamente al hacer click en el, no realiza ninguna acción
> Modificado item tipo tag

- python/main-classic/channels/jkanime.py
- python/main-classic/servers/redirects.py
- python/main-classic/servers/redirects.xml
Agregados redirects para jkanime, animeflv y animeid
Agregado ultimos capitulos para jkanime y uso del findvideos por default
> Agregados redirects y ultimos capitulos a jkanime

- python/main-classic/platformcode/launcher.py
arreglo error ya que no permitia descargar ficheros.
> fix 4.1.0 al llamar a downloads

- python/main-classic/channels/seriesblanco.py
Se arregla filtro para que funcione con calidad "sd"
> Fix 4.1.0 para la calidad en filtertools.

- python/main-classic/channels/pelisdanko.py
- python/main-classic/channels/pelisdanko.xml
Comentado en el foro: http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=7579
> Nuevo canal Pelisdanko

- python/main-classic/channels/beeg.py
- python/main-classic/channels/beeg.xml
- python/main-classic/channels/cinetemagay.py
- python/main-classic/channels/cinetemagay.xml
- python/main-classic/channels/filesmonster_catalogue.py
- python/main-classic/channels/filesmonster_catalogue.xml
- python/main-classic/channels/mocosoftx.py
- python/main-classic/channels/mocosoftx.xml
- python/main-classic/channels/peliculaseroticas.py
- python/main-classic/channels/peliculaseroticas.xml
- python/main-classic/channels/pelisxporno.py
- python/main-classic/channels/pelisxporno.xml
- python/main-classic/channels/pornhub.py
- python/main-classic/channels/pornhub.xml
- python/main-classic/channels/pornoactricesx.py
- python/main-classic/channels/pornoactricesx.xml
- python/main-classic/channels/serviporno.py
- python/main-classic/channels/serviporno.xml
- python/main-classic/channels/submityouflicks.py
- python/main-classic/channels/submityouflicks.xml
- python/main-classic/channels/tubehentai.py
- python/main-classic/channels/tubehentai.xml
- python/main-classic/channels/tupornotv.py
- python/main-classic/channels/tupornotv.xml
- python/main-classic/channels/xhamster.py
- python/main-classic/channels/xhamster.xml
canales para adultos actualizados
añadidos buscadores, categorías, limpiado código y corrección de patrones...
> Varios canales mejorados/reparados

- python/main-classic/platformcode/library.py
daba error al buscar series con este formato "powers (2015)"
> fix 4.1.0 error nombre para la llamada a tmdb

- python/main-classic/servers/allmyvideos.py
- python/main-classic/servers/allmyvideos.xml
- python/main-classic/servers/flashx.py
- python/main-classic/servers/flashx.xml
- python/main-classic/servers/letwatch.py
- python/main-classic/servers/letwatch.xml
- python/main-classic/servers/openload.py
- python/main-classic/servers/openload.xml
- python/main-classic/servers/spruto.py
- python/main-classic/servers/spruto.xml
- python/main-classic/servers/vidspot.py
- python/main-classic/servers/vidspot.xml
- Allmyvideos y vidspot: cargan a través de un proxy.
- Reparados por no funcionar correctamente: Flashx, letwatch, spruto y openload.
Lo subo a develop porque veo la rama master muy desactualizada y no me atrevo :stuck_out_tongue_closed_eyes:
> Reparación de conectores

- python/main-classic/channels/pelispedia.py
- python/main-classic/channels/pelispedia.xml
- python/main-classic/core/tmdb.py
Añadida informacion extra en peliculas y serie.
3 Perfiles de color seleccionables desde la configuracion
Añadidas la seccion Peliculas en el canal Novedades
Desactivadas las busqueda por cambios en la web
> Reparado el canal gracias a las correcciones de @CmosGit

- python/main-classic/channels/cinetux.py
- python/main-classic/channels/cinetux.xml
- python/main-classic/channels/oranline.py
- python/main-classic/channels/oranline.xml
- python/main-classic/channels/pelisdanko.py
Reparado el canal por cambios en la web, además se añaden filtros para el idioma y el tipo de enlaces y se adapta para que se incluya en la sección de Novedades.
Gracias a @superberny70 por el curro con los filtros en tmdb, ha quedado genial :wink: 
Reparado también cinetux siguiendo el mismo formato que oranline.
Aprovecho el PR para hacer un pequeño ajuste en pelisdanko.
> Reparado oranline y cinetux

- python/main-classic/channels/cinetux.py
- python/main-classic/channels/oranline.py
Como el otro PR ya se mergeó, abro este con los cambios que comentaba en el anterior para que detecte en ambos canales cuando no hay enlaces y no se añada la opción de añadir a la biblioteca. En el caso de que sí haya enlaces pero estén filtrados sí aparece la opción y se añadirían todos.
> Cambios finales en oranline y cinetux

- python/main-classic/channels/tvvip.py
- python/main-classic/channels/tvvip.xml
Pues como ya lleva el canal publicado unos días por el foro y no ha dado fallos, lo subo corregido. Además de los cambios oportunos, he modificado la búsqueda global para que filtre los resultados correctamente y adaptado el canal para que funcione todo lo relacionado con la biblioteca tal y como está ahora ahora en develop.
> Reparado tv-vip

- python/main-classic/channels/animeflv.py
- python/main-classic/channels/animeid.py
Agregado anterior y siguiente animeflv, animeid y titulos a animeflv
> Agregado anterior y siguiente animeflv, animeid

- python/main-classic/servers/openload.py
Por nuevos cambios en la web. Gracias a @r0balo :wink:
> Reparado openload

- python/main-classic/channels/animeid.py
reemplazado animeid.moe por animeid.tv ya que punto moe ya no esta disponible
> reemplazado animeid.moe por animeid.tv

- python/main-classic/channels/pepecine.py
cambios por la gestion de infoLabels
> pepecine: update

- python/main-classic/core/tmdb.py
add get_videos: Devuelve una lista ordenada (idioma/resolucion/tipo) de objetos Dict en la que cada uno de sus elementos corresponde con un trailer, teaser o clip de youtube.
> tmdb_update

- python/main-classic/channels/filesmonster_catalogue.py
- python/main-classic/platformcode/library.py
- python/main-classic/servers/filesmonster.xml
Se soluciona el problema con el buscador separándolo para cada una de las  webs, en la versión actual sólo buscaba en una de ellas, curiosamente la que más fallaba de las dos.
> Soluciona el problema con el buscador

- python/main-classic/core/updater.py
@tvalacarta  según lo comentado en #312 vuelvo a subir el updater.py
Comprobado y funciona bien en Kodi y mediaserver
No entiendo cual es el problema que tenias con la versión UI, ya que según las pruebas que he realizado, funciona correctamente también, lo único que para la versión UI el archivo http://descargas.tvalacarta.info/pelisalacarta-ui-version.xml  no es correcto, ya que el valor tag no se corresponde con el valor de versión, y la versión tampoco es la actual (4100) en el fichero remoto hay:
tag -> 4.0.9
versión -> 4011
de modo que no te va a saltar la actualización...
tampoco entiendo por que tienes dos archivos versión.xml en el repositorio, uno en main-classic y otro en main-ui ¿No se supone que los dos son siempre la misma versión? el de main-classic deveria servir para …
> Restaurado updater multiplataforma

- python/main-classic/channels/allpeliculas.py
- python/main-classic/channels/allpeliculas.xml
- python/main-classic/channels/cinetux.py
- python/main-classic/channels/cinetux.xml
- python/main-classic/channels/descargasmix.py
- python/main-classic/channels/descargasmix.xml
- python/main-classic/channels/inkapelis.py
- python/main-classic/channels/inkapelis.xml
- python/main-classic/channels/oranline.py
- python/main-classic/channels/oranline.xml
- python/main-classic/channels/pelisdanko.py
- python/main-classic/channels/pelisdanko.xml
- python/main-classic/channels/seriecanal.py
- python/main-classic/channels/seriecanal.xml
- python/main-classic/channels/trailertools.py
- python/main-classic/channels/tvvip.py
- python/main-classic/channels/tvvip.xml
- python/main-classic/channels/verseriesynovelas.py
- python/main-classic/channels/verseriesynovelas.xml
Como el título indica, principalmente se trata de adaptar varios canales a las nuevas funciones. Y reparar otros como seriecanal que no funcionaba ya que ahora es necesario registrarse en la web para ver los enlaces.
También se incluye un pequeño fix en trailertools junto con el uso de la función get_videos que recientemente incluyó @superberny70 en tmdb.
> Reparados y adaptados varios canales

- python/main-classic/platformcode/mct.py
Daba error por cambio de nombre en método title_to_folder_name en library.
> Corregido MCT

- python/main-classic/core/servertools.py
- python/main-classic/servers/idowatch.py
- python/main-classic/servers/realdebrid.py
- python/main-classic/servers/stormo.py
- python/main-classic/servers/stormo.xml
- Realdebrid falla cuando retorna error o varios enlaces, se corrige en servertools.
- Nuevo conector stormo, se usa en el canal allpeliculas.
- Fix en el regex de idowatch.
> Nuevo conector stormo y corregido realdebrid

- python/main-classic/core/servertools.py
Se modifica el método servertools.is_server_enabled(), ahora comprueba si el servidor está activo y, en el caso de estar habilitada la opción de ocultar servidores de pago sin cuenta, se verifica si se pueden utilizar (son free o tienen cuenta disponible)
Se corrige la función get_server_list() ya que antes no funcionaba correctamente, ahora utiliza el método anterior para devolver los servidores disponibles donde buscar.
> Fallo al comprobar servidores activos en findvideos

- python/main-classic/channels/animeflv.py
- python/main-classic/channels/configuracion.py
- python/main-classic/channels/filtertools.py
- python/main-classic/channels/pelispedia.py
- python/main-classic/channels/seriesflv.py
- python/main-classic/core/scrapertools.py
- python/main-classic/platformcode/xbmc_config_menu.py
- python/main-classic/platformcode/xbmc_info_window.py
> Fix #324 errores

- python/main-classic/platformcode/xbmctools.py
Fallaba debido a que había varios import sys repetidos a lo largo del código cuando ya hace el import al comienzo. He eliminado otros import que también se repetían.
> Error en modo reproduccion SetResolvedUrl

- python/main-classic/channels/filesmonster_catalogue.py
Incluyendo categorías, últimos vídeos y buscador
> Añade la web files-monster.org al canal

- python/main-classic/channels/cinefox.py
- python/main-classic/channels/cinefox.xml
De la web cinefox.cc, comentado en el foro: http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=7746
> Nuevo canal Cinefox

- python/main-classic/channels/cinefox.py
Reparada la función de búsqueda que no mostraba todos los resultados y un bug en la ventana de filtro que se me pasó a raíz de la última modificación.
> Arreglo para cinefox

- python/main-classic/channels/filtertools.py
- python/main-classic/channels/hdfull.py
- python/main-classic/core/filetools.py
- python/main-classic/platformcode/library.py
- python/main-classic/platformcode/mct.py
@tvalacarta por favor mergea esto, gracias.
> Biblioteca fix encoding

- python/main-classic/platformcode/library.py
fix crear strm y marcar como visto en algunos casos
> Biblioteca fixes

- python/main-classic/servers/datoporn.py
- python/main-classic/servers/datoporn.xml
> Nuevo conector datoporn

- python/main-classic/channels/cinefox.py
- python/main-classic/channels/cinefox.xml
- python/main-classic/channels/descargasmix.py
- python/main-classic/channels/oranline.py
- python/main-classic/channels/tvvip.py
- python/main-classic/channels/verseriesynovelas.py
- Reparado descargasmix por cambios en la web.
- Adaptados a los cambios en la biblioteca: cinefox, verseriesynovelas, tv-vip
- Modificada subpaginación en oranline para tmdb
> Retoques en varios canales

- python/main-classic/lib/png.py
- python/main-classic/platformcode/platformtools.py
- python/main-classic/servers/flashx.py
- python/main-classic/servers/gamovideo.py
- python/main-classic/servers/idowatch.py
- python/main-classic/servers/nowvideo.py
- python/main-classic/servers/openload.py
- python/main-classic/servers/powvideo.py
- python/main-classic/servers/videomega.py
- python/main-classic/servers/vidgg.py
Tal y como estaba, el método dialog_numeric devolvía un objeto dialog en lugar del resultado de éste. No es nada urgente ya que por ahora no hay ningún canal que utilice ese método :wink: 
- Reparados openload, videomega, vidgg, idowatch y nowvideo. Añadida detección de subtítulos embebidos en flashx.
- Arreglado también powvideo y gamovideo.
> Fix menor en platformtools - Corregidos varios conectores

- python/main-classic/channels/allpeliculas.py
- python/main-classic/channels/cinefox.py
- python/main-classic/channels/cinetemagay.xml
- python/main-classic/channels/cinetux.py
- python/main-classic/channels/descargasmix.py
- python/main-classic/channels/filesmonster_catalogue.xml
- python/main-classic/channels/inkapelis.py
- python/main-classic/channels/mocosoftx.xml
- python/main-classic/channels/peliculaseroticas.xml
- python/main-classic/channels/pornhub.xml
- python/main-classic/channels/pornoactricesx.xml
- python/main-classic/channels/serviporno.xml
- python/main-classic/channels/submityouflicks.xml
- python/main-classic/channels/tubehentai.xml
- python/main-classic/channels/tupornotv.xml
- python/main-classic/channels/tvvip.py
- python/main-classic/channels/xhamster.xml
- python/main-classic/core/tmdb.py
- Eliminados de películas los canales de adultos. Creo que esto lo comentó @superberny70 hace un tiempo si no me equivoco. No sé cómo lo veis pero me parece que lo mejor es que estos canales estén solamente en su sección.
- Arreglados cinetux, inkapelis y allpeliculas en la parte de la biblioteca. Reparado descargasmix por cambios en la web e incluidos índices por géneros en películas y series.
- En tmdb, ver notas del commit :smile: 
- Reparado tv-vip por cambios en la web.
- Reparado cinefox por cambio de dominio y de código.
> Corregidos varios canales - Fix en tmdb - Eliminados de películas los canales de adultos

- python/version-mediaserver/core/config.py
- python/version-mediaserver/platformcode/launcher.py
Añadir propiedad que necesita otro código común (el channels/configuracion.py)
> [mediaserver] Añadir propiedad que falta para poder abrir la configuración

- python/main-classic/channels/pordede.py
Añadidas opciones para marcar series/peliculas como Siguiente/Pendiente/Finalizadas/Favoritas...
> Marcas Pordede

- python/main-classic/channels/cinecalidad.py
- python/main-classic/channels/cinecalidad.xml
- python/main-classic/channels/locopelis.py
- python/main-classic/channels/locopelis.xml
- python/main-classic/channels/metaserie.py
- python/main-classic/channels/metaserie.xml
- python/main-classic/channels/mundoflv.py
- python/main-classic/channels/mundoflv.xml
- python/main-classic/channels/qserie.py
- python/main-classic/channels/qserie.xml
- python/main-classic/channels/seodiv.py
- python/main-classic/channels/seodiv.xml
Algunos canales propios que me gustaría que se incluyeran en la versión oficial
> Canales nuevos

- python/main-classic/core/item.py
- python/main-classic/core/tmdb.py
- python/main-classic/platformcode/platformtools.py
- python/main-classic/platformcode/xbmc_info_window.py
Podeis consultar los cambios en #381
> Resolviendo conflictos #381

- python/main-classic/channels/cinecalidad.py
- python/main-classic/channels/locopelis.py
- python/main-classic/channels/locopelis.xml
- python/main-classic/channels/metaserie.py
- python/main-classic/channels/metaserie.xml
- python/main-classic/channels/mundoflv.py
- python/main-classic/channels/mundoflv.xml
- python/main-classic/channels/pelisplus.py
- python/main-classic/channels/qserie.py
- python/main-classic/channels/qserie.xml
- python/main-classic/channels/seodiv.py
PelisPlus nuevo canal, y algunos cambios en codigo sugeridos por SeiTaN, ademas correcciones en MundoFLV, Seodiv y LocoPelis
> Ajustes en mis canales

- python/main-classic/core/filetools.py
Actualización de funciones con respecto a lo hablado en issue #377 
He usado "replace" porque en la documentación _https://docs.python.org/2/library/codecs.html#codec-base-classes_ pone que sustituye los caracteres conflictivos por el caracter '?'
> Actualización de las funciones encode y decode de filetools

- python/main-classic/channels/descargasmix.py
- python/main-classic/servers/openload.py
- Arreglado con los últimos cambios de hace unos días. Gracias a robalo por la funcion openload_clean :wink: 
- Reparado descargasmix por cambios en la web.
> Hotfix openload / Descargasmix

- python/main-classic/channels/descargasmix.py
- python/main-classic/channels/verseriesynovelas.py
- python/main-classic/channels/verseriesynovelas.xml
- python/main-classic/servers/flashx.py
- python/main-classic/servers/openload.py
- python/main-classic/servers/speedplay.py
- python/main-classic/servers/speedplay.xml
- python/main-classic/servers/thevideome.py
- python/main-classic/servers/vidgg.py
- python/main-classic/servers/youwatch.py
- Flashx :Reparado por cambios en la página. Tras varios cambios se vuelve a utilizar el método antiguo que dejó de funcionar al ser más rápido, si dejase de hacerlo se intentaría utilizar el actual que es más lento.
- Reparado openload, thevideome, youwatch y vidgg.
- Nuevo conector para la web speedplay.us. Utilizado frecuentemente en el canal verseriesynovelas.
- Añadida detección de enlaces de googlevideo en descargasmix y reparado los enlaces online en series.
- Reparado canal verseriesynovelas, ahora es necesario registrarse para ver los enlaces.
> Hotfix flashx / Openload - Nuevo conector speedplay - Reparados canales

- python/main-classic/channels/configuracion.py
- python/main-classic/core/ziptools.py
- Se añade la opción de actualizar desde una url de github que apunte a la carpeta channels o servers completa, pensada para usuarios más avanzados.
- Modificado el sistema de backups, ahora se crea una carpeta por cada proceso dentro de addon_data/plugin.video.pelisalacarta/backups.
- Añadidas dos opciones en el menú, para mostrar la ruta de la carpeta backups y para eliminar su contenido.
> Mejora en actualizacion de canales/conectores desde url en canal configuracion

- python/main-classic/core/scrapertools.py
Añadir método para que retorne el result code.
Es "downloadpage" pero retornando, además de los datos leídos, el result code.
El original downloadpage se comporta igual que antes, pero delega en el nuevo método (que era su antiguo cuerpo) e ignora el result code.
> Añadir downloadPageWithResult

- python/main-classic/core/servertools.py
- python/main-classic/servers/alldebrid.py
El conector fallaba debido a los cambios en servertools. Se adapta también este último para que reconozca correctamente los mensajes de error de alldebrid y realdebrid.
> Reparado alldebrid

- python/main-classic/channels/cinecalidad.py
- python/main-classic/channels/pelisplus.py
- python/main-classic/channels/pelisplus.xml
> ajustes en cinecalidad, seodiv y busqueda en PelisPlus

- python/main-classic/core/downloadtools.py
- No usa directamente  librtmp ya que parece que el import no siempre está disponible.
- Lanza un subproceso con rtmpdump. En Windows es necesario instalarlo.
- No usa threads así que no muestra ninguna barra de progreso ni tampoco se marca el final real de la descarga en el log info.
Lo he probado con Frodo en windows xp y openlec 6.0.3 en raspberry con la última versión (4.0.3) estable liberada.del plugin que usa para los diálogos:
`import xbmcgui`
`advertencia = xbmcgui.Dialog()`
`resultado = advertencia.ok(...)`
que para el pull request he tenido que substituir "al vuelo" por los:
`from platformcode import platformtools`
`advertencia = platformtools.dialog_ok(...)`
ya que no funcionan con mi instalación. Espero que sirva.
> ImportError: cannot import name platformtools
> Soporte preliminar de descarga RTMP con rtmpdump

- python/main-classic/core/channeltools.py
Solución para https://github.com/tvalacarta/pelisalacarta/issues/410
> Fix encoding al salvar el archivo buscador_data.json

- python/main-classic/servers/flashx.py
- python/main-classic/servers/openload.py
Enésimo cambio que hacen en ambos servers xD
> Reparado openload y flashx

- python/main-classic/channels/inkapelis.py
- python/main-classic/channels/inkapelis.xml
- python/main-classic/channels/trailertools.py
- python/main-classic/channels/verseriesynovelas.py
- python/main-classic/servers/dailymotion.py
- python/main-classic/servers/speedplay.py
- Corregidos algunos fallitos en verseriesynovelas y trailertools.
- Mejorada expresion regular en speedplay
- Añadido filtro de peliculas en inkapelis
- Corregido conector dailymotion
> Fixes varios canales

- python/main-classic/channels/newpct1.py
Fix debido a los cambios en el ultimo commit que hice para el tema de los menus contextuales en el canal, en algunas peliculas más antiguas daba error.
> Fix newpct1

- python/main-classic/channels/filtertools.py
- python/main-classic/platformcode/xbmc_config_menu.py
@tvalacarta no esperaba que lo mergearas tan rápido!! 
Añado unas correcciones que faltaban.
> Ultimos ajustes en ventanas

- python/main-classic/channels/seriecanal.py
- python/main-classic/servers/datoporn.py
- python/main-classic/servers/flashx.py
- python/main-classic/servers/gamovideo.py
- python/main-classic/servers/openload.py
- python/main-classic/servers/powvideo.py
- python/main-classic/servers/vidgg.py
- python/main-classic/servers/youwatch.py
- Reparados por cambios en las webs: datoporn, gamovideo, vidgg, powvideo y youwatch.
- Mejorado el código en openload para evitar algunos errores y en el método para usar la api. Gracias a zastilla por su ayuda 😉
> Varios conectores reparados

- python/check.py
- python/main-classic/channels/animeflv_me.py
- python/main-classic/channels/aquitorrent.py
- python/main-classic/channels/beeg.py
- python/main-classic/channels/cinefox.py
- python/main-classic/channels/filtertools.py
- python/main-classic/channels/inkapelis.py
- python/main-classic/channels/mitube.py
- python/main-classic/channels/oranline.py
- python/main-classic/channels/pepecine.py
- python/main-classic/channels/pornhub.py
- python/main-classic/channels/seriesblanco.py
- python/main-classic/channels/trailertools.py
- python/main-classic/channels/tremendaseries.py
- python/main-classic/core/jsontools.py
- python/main-classic/lib/btserver/__init__.py
- python/main-classic/lib/btserver/cache.py
- python/main-classic/lib/btserver/client.py
- python/main-classic/lib/btserver/cursor.py
- python/main-classic/lib/btserver/dispatcher.py
- python/main-classic/lib/btserver/file.py
- python/main-classic/lib/btserver/handler.py
- python/main-classic/lib/btserver/monitor.py
- python/main-classic/lib/btserver/resume_data.py
- python/main-classic/lib/btserver/server.py
- python/main-classic/platformcode/platformtools.py
- python/main-classic/platformcode/xbmc_config_menu.py
- Modificado todos los canales y servers que tenían código no compatible con Python 2.4 para hacerlo compatible
- Modificado cliente torrent: 
- Eliminado código no compatible con Python 2.4 (aunque para que funcione en Python 2.4 hará falta conseguir libtorrent para Python 2.4 que no se si existe)
- Mejorado gestión del buffer, ahora no debería fallar a veces al comenzar la reproducción
- Reordenación y limpieza del código
- Modificado jsontools, fallaba en xbmc 10 y desconozco si en alguno mas
- Corregidos dos pequeños fallos en xbmc_config_menu
> Mejoras para compatibilidad

- python/check.py
- python/main-classic/platformcode/download_and_play.py
- python/main-classic/servers/gamovideo.py
- python/main-classic/servers/openload.py
Pongo aquí algunos cambios que faltaban en el PR anterior
Quedan todavía unas cuantas, concretamente:
- update_server.py (creo que este modulo no se usa por eso no lo he tocado)
- mct.py (no acabo de entender esa parte del código por eso no lo he tocado, tengo que mirármelo con mas calma, de todas formas creo que libtorrent no esta para Python 2.4)
- Algunas librerías de la carpeta lib: requests, sambatools, pafy, megaserver (Lo mismo, hay que mirarselas con calma, y tampoco se si solo modificando eso serán compatibles, hay que probarlo)
- descargas.py (esto ya esta modificado en el update que se va ha hacer con la biblioteca)
No era mi intención de momento, pero en el PR anterior se me coló un archivo check,py, asi que ya que esta lo dejo y lo actualizo:
Este archivo lo que hace es que …
> Pequeños cambios para compatibilidad

- python/main-classic/channels/aquitorrent.py
- python/main-classic/servers/adfly.py
He reparado el conector para Adf.ly y lo he añadido al canal aquitorrent, ya que los enlaces vienen en adf.ly y no funcionaban...
el conector Adf.ly lo he probado con varios enlaces y parece que funciona bien, pero no puedo asergurar que funcione con todos, habrá que ir probando...
> Adf.ly y canal aquitorrent

- python/main-classic/channels/biblioteca.py
- python/main-classic/channels/filtertools.py
- python/main-classic/library_service.py
- python/main-classic/platformcode/library.py
- Correcciones para poder usar la biblioteca con filtertools.
- Comprobaciones en el marcado de episodios para que tb añada temporadas/serie como vista.
Serie
Temporada
Episodios, se marca el último episodio como marcado
El episodio se marca correctamente
La temporada tb se marca
Y la serie tb se marca
Estas comprobaciones tb se hacen si se marca una temporada, comprobando la serie.
Si se desmarca episodios / temporadas tb se desmarca la serie como vista.
**Si se añaden nuevos episodios a la biblioteca, tb se marcará la temporada(ya estaba) y la serie como no vista.**
> Mejoras en la biblioteca de pelisalacarta

- python/main-classic/channels/trailertools.py
- python/main-classic/lib/jsinterpreter.py
- python/main-classic/platformcode/platformtools.py
- python/main-classic/platformcode/xbmc_config_menu.py
- python/main-classic/servers/nosvideo.py
- python/main-classic/servers/youtube.py
- Fix en xbmc_config_menu para que detecte los cambios que se hagan en los controles tipo list de la ventana mediante el teclado.
- El conector de youtube no extraía correctamente los enlaces con firma encriptada (ej de vídeo que no funcionaba: https://www.youtube.com/watch?v=1aV9X2d-f5g). Para desencriptar la firma, se utiliza una librería intérprete de javascript (gracias youtube-dl! 😄 )
- Leves mejoras en trailertools. Relacionado con esto he modificado el menú contextual Buscar Trailer para que se añada por defecto en items con action "findvideos", de esta manera se integra en todos los canales aunque no tengan específicamente esa opción puesto que el canal está preparado para hacer búsquedas manuales y por diferentes criterios.
- Reparado nosvideo.
> Varios cambios (fix xbmc_config_menu, conector youtube, trailertools)

- python/main-classic/channels/megaforo.xml
- python/main-classic/channels/megahd.xml
- python/main-classic/channels/peliculasmx.py
- python/main-classic/channels/peliculasmx.xml
- python/main-classic/channels/pelisadicto.py
- python/main-classic/channels/reyanime.py
- python/main-classic/channels/verseriesonlinetv.xml
- python/main-classic/channels/vseries.xml
- python/main-classic/channels/yaske.py
Reparados: PeliculasMX, ReyAnime, Yaske y PelisAdictos
Desactivados: Megaforo, MegaHD, Vseries y VerSeriesOnline
Pendientes: multicineonline
Gracias por el [aviso](http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=7985&p=35757#p35429) dan83
> Fix varios canales

- python/main-classic/servers/openload.py
Incluyo los cambios que estaban pendientes por dar conflicto el anterior PR.
> Hotfix openload

- python/main-classic/default.py
- python/version-boxee/core/config.py
Reparados dos fallos al hacer los cambios para compatibilidad:
- Fallo al entrar a pelisalacarta desde el home
- Fallo en boxee al quedar unas líneas comentadas por error
> Fix fallos compatibilidad

- python/main-classic/servers/datoporn.py
- python/main-classic/servers/powvideo.py
- python/main-classic/servers/streamplay.py
Reparados / modificados servidores:
- Powvideo: Reparado, decía siempre que no existe el archivo
- Streamplay: Reparado, decía siempre que no existe el archivo
- Datoporn: Modificado, ahora en vez de devolver un .m3u8 devuelve .mp4 con las diferentes resoluciones disponibles.
> Servidores reparados [powvideo, streamplay, datoporn]

- python/main-classic/channels/cinecalidad.py
- python/main-classic/channels/locopelis.py
- python/main-classic/channels/metaserie.py
- python/main-classic/channels/mundoflv.py
- python/main-classic/channels/pelisplus.py
- python/main-classic/channels/qserie.py
- python/main-classic/channels/seodiv.py
Agregada la compatibilidad con la nueva biblioteca en: CineCalidad,, LocoPelis, Metaserie, MundoFlv, PelisPlus, QSerie y Seodiv
> Compatibilidad para biblioteca en varios canales

- python/main-classic/channels/puyasubs.py
- python/main-classic/channels/puyasubs.xml
- python/main-classic/lib/megaserver/client.py
Además del canal, se adapta la librería client del conector de mega para la reproducción de archivos en carpetas, puesto que el canal contiene varios de ese tipo. Muchas gracias a @divadres por toda la ayuda 😉
> Nuevo canal Puyasubs

- python/main-classic/channels/hentaiid.py
- python/main-classic/channels/hentaiid.xml
Añadido canal por petición en el foro.
> Nuevo canal [Adultos]HentaiID

- python/main-classic/platformcode/mct.py
A los últimos cambios realizados por robalo en su repo: https://github.com/r0balo/mct_kodi_pelisalacarta/blob/master/platformcode/mct.py
Entre otras cosas se añade mayor compatibilidad según el SO, guardado de magnets en .torrent, comprobación de archivos soportados en torrents multiarchivos, porcentaje de piezas finales para el inicio de la reproducción, descarga de torrents si la url pasa por adf.ly...
> Actualización MCT

- python/main-classic/core/filetools.py
reescrita la funcion text2filename
> solucionado bug con las tildes en MacOs

- python/main-classic/channels/seriesblanco.py
- python/main-classic/channels/seriesblanco.xml
- python/main-classic/channels/seriesdanko.py
Y arreglar la codificación de las novedades haciendo un test de utf-8
> Añadir seriesblanco a novedades

- python/main-classic/channels/hdfull.py
Modificado header user-agent para que HDFull vuelva a funcionar
> HDFull reparado

- python/main-classic/servers/flashx.py
- python/main-classic/servers/openload.py
- python/main-classic/servers/streamplay.py
Gracias a robalo por el arreglo de streamplay y flashx 😉
> Fix openload, flashx y streamplay

- python/main-classic/core/filetools.py
@SeiTaN según la conversación del #474 modifico el encoding a Unicode en Windows, prueba si así te crea las carpetas bien
EDITO: también hay una corrección sobre la función filetools.copy() que estaba realizando
> fix caracteres no ASCII en windows

- python/main-classic/library_service.py
- python/main-classic/platformcode/xbmc_library.py
No existe el método al que llama.
> Arreglada la llamada a un método que estropea la actualización de las series al inicio de Kodi. Arreglado también un import.

- python/main-classic/miltorrents.py
- python/main-classic/miltorrents.xml
- python/main-classic/pasateatorrent.py
- python/main-classic/pasateatorrent.xml
- python/main-classic/peliculasdk.py
- python/main-classic/peliculasdk.xml
- python/main-classic/txibitsoft.py
- python/main-classic/txibitsoft.xml
- python/main-classic/zentorrents.py
- python/main-classic/zentorrents.xml
Actualización Zentorrent,Txibisoft, Peliculasdk. Dos nuevos canales Pasateatorrent y miltorrent
> Actualización varios canales y dos nuevos

- python/version-mediaserver/platformcode/template/css/pelisalacarta.css
- python/version-mediaserver/platformcode/template/js/navigation.js
- python/version-mediaserver/platformcode/template/js/popups.js
- python/version-mediaserver/platformcode/template/page.html
Soluciona el problema que el video sigue sonando cuando cierras el reproductor en algunos navegadores...
> [mediaserver] - fix video sigue sonando al cerrar la ventana

- python/version-mediaserver/platformcode/controllers/html.py
- soluciona un problema en la versión mediaserver que ponía la cpu al 100% por un bucle infinito
- mejora la gestión del bulce para esperar los datos incluyendo un sleep()
> [mediaserver] - fix bucle infinito

- python/main-classic/channels/infoplus.py
- python/main-classic/servers/flashx.py
- python/main-classic/servers/youtube.py
Corregido fallo con los logos y nueva ventana de diálogo para evitar cargar varias ventanas del mismo tipo.
Como es algo casi anecdótico, añado a este PR un fix para flashx para no abrir uno nuevo 😉
> Solucionados errores menores en infoplus / Fix menor en flashx / Mejoras en youtube

- python/main-classic/channels/cuelgame.py
- python/main-classic/channels/cuelgame.xml
- python/main-classic/channels/pasateatorrent.py
- python/main-classic/channels/peliculasdk.py
Se arregla la obtención del log infoplus cuando no hay en Fanart.tv .
Actualización Cuélgame y adaptación infoplus
> Corrección PelisDk y Update Cuelgáme

- python/main-classic/channels/mundoflv.py
- python/main-classic/channels/pymovie.py
- python/main-classic/channels/pymovie.xml
Reparada la funcion de busqueda por que no encontraba los enlaces a los videos
> Nuevo Canal pymovie y reparada la funcion de busqueda en MundoFLV

- python/main-classic/channels/cinetux.py
- python/main-classic/channels/pordede.py
- python/main-classic/channels/seriesdanko.py
- python/main-classic/platformcode/mct.py
- python/main-classic/servers/nowvideo.py
- python/main-classic/servers/powvideo.py
- python/main-classic/servers/streaminto.py
- python/main-classic/servers/streamplay.py
- python/main-classic/servers/youtube.py
Gracias a @r0balo por los arreglos de pordede y streaminto 😉 
En cinetux se corrige el menú de generos que no funcionaba, y en MCT la parte de guardado de archivos magnets mejorando la expresión regular que en ocasiones podía fallar.
> Varios arreglos (pordede, streaminto, cinetux, seriesdanko, MCT)

- python/main-classic/core/item.py
> Arreglar el parseado de URL's no base64

- python/main-classic/core/library.py
- python/main-classic/library_service.py
fijar canal y accion en tvshow.nfo
> Bug al convertir la biblioteca de series desde la version 4.1.2 

- python/main-classic/channels/aquitorrent.py
- python/main-classic/channels/cuelgame.py
- python/main-classic/channels/miltorrents.py
- python/main-classic/channels/pasateatorrent.py
- python/main-classic/channels/peliculasdk.py
- python/main-classic/channels/txibitsoft.py
- python/main-classic/channels/verseriesonlinetv.py
- python/main-classic/channels/zentorrents.py
Nuevos cambios Web en series. Se reestructura código.
En la última semana han cambiado dos veces las urls incluyendo “-“ ,
luego se suprimen , redireccionando urls…Esperemos que sea el cambio
definitivo.
> FIx-2-Pasateatorrent

- python/main-classic/channels/peliculasaudiolatino.py
Agregado anti_cloudflare, ya funciona
> FIX peliculasaudiolatino.py

- python/main-classic/channels/divxatope.py
En este canal se hace el add item sin haber asignado (en algunos casos) estas variables, por lo que petaba.
Podéis comprobarlo buscando "star" por ejemplo.
> Fix search

- python/main-classic/channels/seriesblanco.py
> Seriesblanco: Arregla una expresión regular de un canal

- python/main-classic/channels/torrentlocura.py
- python/main-classic/channels/torrentlocura.xml
Realmente nuevo ,nuevo no es lo es correcto. Se trata de una nueva
versión de divatope, el cual ya viene clocado de newptc. Pero en fin ,
como sabe la providencia cual de ellos queda´ra l a final, cual caerá o
no, pues aquí una opción más ;)
> Nuevo canal Torrentlocura

- python/main-classic/channels/vidz7.py
- python/main-classic/channels/vidz7.xml
Nuevo canal de contenido adulto en HD
> Nuevo canal Vidz7

- python/main-classic/channels/divxatope.py
- python/main-classic/channels/divxatope.xml
- python/main-classic/channels/newpct1.py
- python/main-classic/channels/newpct1.xml
Sustituye a la PR #522 por duplicidad en los cambios de seriesblanco #521
> Newpct1 y DivXatope: adaptados por cambios en la web 

- python/main-classic/channels/erotik.py
- python/main-classic/channels/erotik.xml
Canal para adultos enviado al foro por jvc99: http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=8472
> Añadimos el canal EROTIK

- python/main-classic/platformcode/xbmc_config_menu.py
- python/main-classic/resources/skins/Default/720p/ChannelSettings.xml
He adaptado la ventana para que se pueda hacer scroll en dispositivos táctiles.
No funciona todo lo fino que me gustaría y tengo que buscar un método definitivo que funcione mejor, pero mientras tanto, se puede usar.
Recomiendo moverlo suave, así funciona mejor mientras termino de adaptarlo...
> [Ventana configuracion] Scroll en dispositivos tactiles

- python/main-classic/channels/seriesdanko.py
- python/main-classic/servers/thevideos.py
conector -thevideos-
- se extrae tb los subtitulos del servidor.
- limpieza de codigo actualizado a 4.2.0
- cambiada llamada a httptools.
¿Hay que modificar tb el xml del server?
> fix seriesdanko, servidor [thevideos]

- python/main-classic/channels/canalporno.py
- python/main-classic/channels/canalporno.xml
- python/main-classic/channels/cineasiaenlinea.py
- python/main-classic/channels/cineasiaenlinea.xml
- python/main-classic/channels/clasicofilm.py
- python/main-classic/channels/clasicofilm.xml
- python/main-classic/channels/playmax.py
- python/main-classic/channels/playmax.xml
- python/main-classic/servers/openload.py
- python/main-classic/servers/openload.xml
- python/main-classic/servers/streamplay.py
- python/main-classic/servers/vk.py
- python/main-classic/servers/vk.xml
- python/main-classic/servers/watchers.py
- python/main-classic/servers/watchers.xml
- python/main-classic/servers/zstream.py
- python/main-classic/servers/zstream.xml
Nuevos canales: cineasiaenlinea, clasicofilm, playmax y canalporno. Comentado en el foro: http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=8566
Nuevos conectores: watchers y zstream.
Arreglo conectores: openload, vk, streamplay.
> Nuevos canales, conectores y arreglos

- python/main-classic/channels/tvmoviedb.py
- python/main-classic/channels/tvmoviedb.xml
- python/main-classic/resources/settings.xml
- python/main-classic/servers/crunchyroll.py
- python/main-classic/servers/crunchyroll.xml
Nuevo canal tvmoviedb, conector para crunchyroll y modificado settings.xml para el premium y el idioma de los subs de crunchy. Explicado todas las opciones y funciones del canal en el foro: http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=8541
Algunos compañeros, debido a la naturaleza del canal, han sugerido que se podría añadir como una nueva categoría en el menú principal en lugar de en la habitual lista de canales. Yo lo he subido como un canal normal, pero si ves @tvalacarta que es una buena idea y encaja en situarlo como una sección aparte pues lo modifico y listo 😉
> Canal tvmoviedb y conector crunchyroll

- python/main-classic/channels/divxatope.py
- python/main-classic/channels/divxatope.xml
- Añadida seccion Peliculas 4K ultraHD
- Reparados los enlaces de torrents que antes no se mostraban.
- Reparada la paginacion
> [DivXatope] Añadida seccion Peliculas 4K

- python/main-classic/channels/pasateatorrent.py
- python/main-classic/channels/pasateatorrent.xml
- python/main-classic/channels/peliculasgratis.py
- python/main-classic/channels/peliculasgratis.xml
Se arregla s que se cuela en xml en todos los canales subidos en este PR
> Corrección cagada: Torrentlocura,Pasateatorrent y Pelisgratis

- python/main-classic/channels/mundoflv.py
- python/main-classic/channels/mundoflv.xml
MundoFlv: Solucionado problema con el listado de enlaces
> fix en la búsqueda de enlaces

- python/main-classic/channels/torrentlocura.py
Mejoras en buscador del canal y en el “lidiar” con tildes y ñ
> Mejoras Torrentlocura

- python/main-classic/channels/youpeliculas.py
- python/main-classic/channels/youpeliculas.xml
- Nuevo Canal de Peliculas, Series, Animes
- Usa httools.py, jsontools.py
> [Nuevo Canal] YouPeliculas.co

- python/main-classic/servers/powvideo.py
- python/main-classic/servers/powvideo.xml
- python/main-classic/servers/streamplay.py
- python/main-classic/servers/streamplay.xml
Se adaptan al uso de httptools y se introduce el método jhexdecode gracias a robalo 😉
> Reparados y mejorados powvideo y streamplay

- python/main-classic/channels/configuracion.py
- python/main-classic/channels/descargas.py
- python/main-classic/channels/descargas.xml
- python/main-classic/lib/sambatools/libsmb.py
Intentando añadir las sugerencias de #555:
- Añadido ajuestes para:
- Pasar o no las descargas a la biblioteca
- Activar visualización de archivos descargados desde el canal descargas
- Corregidos algunos fallos
> Mejoras descargas

- python/main-classic/lib/btserver/cache.py
Para que se creen todos los directorios padre.
> [libtorrent client] Usar mkdirs para crear el directorio cache

- python/main-classic/channels/seriesblanco.py
- python/main-classic/channels/seriesblanco.xml
Evita que coja otros datos de la página como si fueran series.
> Limitando RE

- python/main-classic/core/logger.py
Cuando message era un list o un dict vacios se producia un error
> Fix logger

- python/main-classic/channels/seriesflv.py
- python/main-classic/channels/seriesflv.xml
Más información en los commits.
> [seriesflv] Añadido listado alfabético y uso de httptools

- python/main-classic/core/servertools.py
Gracias a kerenmac por detectarlo y por el arreglo 😉
> Fix #603 error conversion xml a json en servertools

- python/main-classic/platformcode/platformtools.py
- python/main-classic/servers/youtube.py
- python/main-classic/servers/youtube.xml
...para poder ver vídeos en calidades de 1080p y superiores, a través del addon inputstream de Kodi 17.
Para ello se modifica platformtools de forma que detecte si hay que añadirle al listitem de reproducción, los parámetros necesarios para que se reproduzca a través de dicho addon.
> Adaptado youtube para reproducir mpd

- python/main-classic/channels/animeid.py
- python/main-classic/servers/redirects.py
fix redirects animeflv y fix novedades animeid
> fix redirects animeflv y fix novedades animeid

- python/main-classic/channels/yaske.py
- python/main-classic/channels/yaske.xml
- python/main-classic/platformcode/platformtools.py
- Añadidas mejoras visuales e informacion de tmdb en las peliculas.
- Dehabilitado en platformtools el menu contextual en los items del tipo "Buscar Trailer"
- Añadida opcion en platformtools para deshabilitar el menu contextual de pelisalacarta: 
> Se pueden deshabilitar las opciones del menu contextual añadiendo un comando 'no_context' al item.context.
Las opciones que Kodi, el skin u otro añadido añadan al menu contextual no se pueden deshabilitar.
> [Yaske] Mejoras visuales y pequeños cambios en platformtools

- python/main-classic/channels/copiapop.py
- python/main-classic/channels/copiapop.xml
- python/main-classic/channels/nuvid.py
- python/main-classic/channels/nuvid.xml
- python/main-classic/channels/peliculasnu.py
- python/main-classic/channels/peliculasnu.xml
- python/main-classic/channels/tvmoviedb.py
- python/main-classic/servers/copiapop.py
- python/main-classic/servers/copiapop.xml
- python/main-classic/servers/fastplay.py
- python/main-classic/servers/fastplay.xml
- python/main-classic/servers/raptu.py
- python/main-classic/servers/raptu.xml
Canales: Copiapop, peliculasnu y nuvid
Servidores: Copiapop, fastplay y raptu
Comentado en el foro: http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=8696
Reparado algunos apartados e imports de tvmoviedb
> Nuevos canales y servidores

- python/main-classic/core/config.py
- python/main-classic/platformcode/xbmc_library.py
No lo mergearon en la que lo puse para mergear, así que ahora hay que hacerlo en develop.
Esto arregla la autoconfiguración ya que pilla el valor de la config, en vez de hardcodear una ruta.
> Fix autoconfig

- python/main-classic/channels/biblioteca.py
- python/main-classic/core/library.py
- python/main-classic/core/tmdb.py
- python/main-classic/core/tvdb.py
Arreglos varios:
- Añadir series desde tmdb.
- Añadir series desde tvdb cuando el plot introduce saltos de línea.
- Solucionado fallo al marcar series como vista desde la bibliotea de pelis.
- Si da error al introducir una serie no se ejecuta el escaneo.
> Fix biblioteca

- python/main-classic/channels/datoporn.py
- python/main-classic/channels/datoporn.xml
- python/main-classic/channels/pelismagnet.py
- python/main-classic/channels/pelismagnet.xml
- python/main-classic/channels/pelisxporno.py
- python/main-classic/channels/pelisxporno.xml
- python/main-classic/servers/datoporn.py
- python/main-classic/servers/datoporn.xml
También se mejora/actualiza el canal pelisxporno.
Añado el arreglo también de pelismagnet que se me había pasado. El canal ahora usa proxy para conectar porque se ha cambiado la api (y la web al completo) a un servidor https (ssl) y python siempre tira error al intentar abrir la página. He añadido la opción para buscar la info en Tmdb y reducido los items por página a la mitad, 25.
> Nuevo canal datoporn y arreglado el conector (y pelismagnet)

- python/main-classic/platformcode/platformtools.py
- python/version-xbmc-09-plugin/core/config.py
Se solucionan dos fallos en la versión XBMC 9
> [XBMC 9] - Solucionados dos fallos

- python/main-classic/core/config.py
- python/main-classic/platformcode/xbmc_helpers.py
- python/main-classic/platformcode/xbmc_library.py
PR en un solo commit para tener una fácil eliminación del mismo.
> Recuperar el path de la libreria al cargar el addon (autoconfiguración)

- python/main-classic/channels/allpeliculas.py
- python/main-classic/channels/areadocumental.py
- python/main-classic/channels/cineasiaenlinea.py
- python/main-classic/channels/cinefox.py
- python/main-classic/channels/cinetux.py
- python/main-classic/channels/clasicofilm.py
- python/main-classic/channels/copiapop.py
- python/main-classic/channels/descargasmix.py
- python/main-classic/channels/inkapelis.py
- python/main-classic/channels/peliculasnu.py
- python/main-classic/channels/pelisdanko.py
- python/main-classic/channels/pelismagnet.py
- python/main-classic/channels/playmax.py
- python/main-classic/channels/puyasubs.py
- python/main-classic/channels/seriecanal.py
- python/main-classic/channels/tvmoviedb.py
- python/main-classic/channels/verseriesynovelas.py
- python/main-classic/channels/vixto.py
La ventana de configuración de estos canales no funcionaba en plex debido a que no se retornaba.
> Corregido menu configuracion en canales para plex

- python/build.xml
- python/main-classic/core/api.py
- python/main-classic/core/config.py
- python/main-classic/library_service.py
- python/main-classic/platformcode/launcher.py
- python/main-classic/platformcode/platformtools.py
- python/main-classic/platformcode/xbmc_helpers.py
- python/main-classic/servers/youtube.py
- python/version-boxee/core/config.py
- python/version-command-line/core/config.py
- python/version-mediaserver/core/config.py
- python/version-plex/core/config.py
- python/version-xbmc-09-plugin/core/config.py
Tal y como explique en su dia en la #391 he sustituido las constantes por una funciona q retorna el valor correcto.
> [Fix #391] get_platform

- python/main-classic/core/servertools.py
Corregido problema con importscon cuenta Premium en los propios servidores producido al mover los debriders de ubicación.
> fix servertools

- python/main-classic/servers/openload.py
> Fix openload

- python/main-classic/channels/animeflv_me.py
> Se adicionó la opción ultimos diferente a novedades

- python/main-classic/core/config.py
Pues eso q daba problemas con las versiones Beta y RC de Kodi
Gracias a @SeiTaN  por comentarlo.
> [fix get_platform] Corregido error en betas y RC

- python/main-classic/channels/biblioteca.xml
- python/main-classic/core/library.py
- python/main-classic/library_service.py
Reordenar y aclarar conceptos en las preferencias sobre las actualizaciones de la biblioteca
> [FIX #661]cambios en el cuadro de configuracion de la biblioteca

- python/main-classic/channels/allpeliculas.py
- python/main-classic/channels/cinetux.py
- python/main-classic/channels/inkapelis.py
- python/main-classic/channels/inkapelis.xml
- python/main-classic/channels/peliculasnu.py
- python/main-classic/servers/filez.py
- python/main-classic/servers/filez.xml
- python/main-classic/servers/spruto.xml
- python/main-classic/servers/thevideome.py
- python/main-classic/servers/wholecloud.py
- python/main-classic/servers/wholecloud.xml
En varios canales: allpeliculas, cinetux y peliculasnu. En inkapelis se añaden porque no los había.
Reparados thevideome y spruto ya que no funcionaban. Añadido conector wholecloud (se puede probar en pelisdanko o hdfull) y filez.tv (seriesblanco)
> Reparados enlaces directos y conectores + 2 nuevos conectores

- python/main-classic/channels/animeflv.py
- python/main-classic/channels/animeflv.xml
- python/main-classic/channels/animeflv_ru.py
- python/main-classic/channels/animeflv_ru.xml
- python/main-classic/channels/renumbertools.py
> Fix animeflv.net, nuevo canal animeflv.ru

- python/main-classic/servers/cloudy.py
- python/main-classic/servers/cloudy.xml
- python/main-classic/servers/mailru.py
- python/main-classic/servers/mailru.xml
- python/main-classic/servers/nowvideo.py
- python/main-classic/servers/nowvideo.xml
- python/main-classic/servers/openload.py
- python/main-classic/servers/openload.xml
- python/main-classic/servers/vimpleru.py
- python/main-classic/servers/vimpleru.xml
- python/main-classic/servers/yourupload.py
- python/main-classic/servers/yourupload.xml
- python/main-classic/servers/zippyshare.py
- python/main-classic/servers/zippyshare.xml
Zippyshare se añade también como free ya que antes solo podía usarse junto a servidores premium.
Corregidos varios conectores más: cloudy, vimpleru, mailru y yourupload
> Corregidos openload, nowvideo y zippyshare

- python/main-classic/channels/hdfull.py
- python/main-classic/servers/nowvideo.py
- python/main-classic/servers/okru.py
- python/main-classic/servers/openload.py
Hdfull fallaba en el método findvideos por un cambio en la ofuscación de los enlaces.
Openload lo habitual xD
Corregido nowvideo y okru
> Corregidos canal hdfull y conector openload y nowvideo

- python/main-classic/servers/streamcloud.py
- python/main-classic/servers/streamcloud.xml
Streamcloud - No detectaba archivos borrados y limpiados los logger.info :)
> Streamcloud - No detectaba archivos borrados

- python/main-classic/servers/powvideo.py
- python/main-classic/servers/powvideo.xml
No mostraba mensaje cuando un archivo había sido borrado por no respetar los términos de uso
> Powvideo - Archivo borrado

- python/main-classic/channels/estadepelis.py
- python/main-classic/channels/estadepelis.xml
- python/main-classic/channels/floow.py
- python/main-classic/channels/floow.xml
- python/main-classic/channels/pelisplus.py
- python/main-classic/channels/pelisplus.xml
- python/main-classic/channels/serieslatino.py
- python/main-classic/channels/serieslatino.xml
Ademas fixes y adiciones a Estadepelis y Pelisplus
> Nuevos canales SeriesLatino y Floow.

- python/main-classic/core/config.py
- python/main-classic/core/library.py
- python/main-classic/platformcode/xbmc_library.py
- python/main-classic/resources/settings.xml
Este PR viene de un propuesta de @tvalacarta en el foro: http://www.mimediacenter.info/foro/viewtopic.php?f=14&p=40776#p40713
Se ha diferenciado el proceso de creacion de carpetas con la insercion en la BD. Mientras q lo primero se hace siempre, con independencia de q se use o no la biblioteca, la insercion en la BD y por consiguiente la instalacion de los addons themoviedb y TheTVdb (si es necesario) solo se hacen la primera vez q intentamos añadir una serie/pelicula. A no ser q lo activemos en preferencias manualmente.
Como veis el texto del cuadro es provisional. No se me ocurria q poner, jajaja. 
Por otra parte, ahora se añaden las rutas librarypath y downloadpath (esta ultima si no la quereis la quitamos) al archivo sources.xml, por lo q **tras reiniciar** las tendermos disponibles …
> [Biblioteca] Preguntar antes de lanzar el auto-configurador

- python/main-classic/channels/biblioteca.py
Corregido un fallo que impedía que se reprodujeran los videos descargados en la biblioteca
> Fix reproducir descargas en biblioteca

- python/main-classic/core/servertools.py
- python/main-classic/servers/debriders/alldebrid.xml
- python/main-classic/servers/debriders/realdebrid.xml
Se producia un error al mostrar el mensaje "...necesitas una cuenta en..." en servertools a raíz de eliminar los XML de alldebrid y realdebrid por error...
> [servertools] corregido error al mostrar mensaje de cuentas premium

- python/main-classic/channels/crimenes.py
Arreglo de la paginación. Sólo estaba devolviendo los primeros 20 items de la búsqueda por cambios en el diseño de la plantilla de youtube...y no encontraba el campo de paginación para añadir el item "siguiente".
> Fix crimenes.py

- python/main-classic/channels/filtertools.py
- python/main-classic/core/tvdb.py
- python/main-classic/resources/settings.xml
- python/version-mediaserver/platformcode/controllers/html.py
- python/version-mediaserver/platformcode/template/js/dialogs.js
- python/version-mediaserver/platformcode/template/js/vars.js
- fix import en tvdb.
- cambiados textos referentes a la biblioteca.
- se permite usar filtertools en mediaserver, se corrigen errores.
> [fix 4.2.0beta 3]pequeñas correcciones

- python/main-classic/channelselector.py
Corregido bug: http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=8928&p=41613#p41613
> FIX filterchannels

- python/main-classic/channels/biblioteca.py
- python/main-classic/library_service.py
- python/main-classic/platformcode/xbmc_library.py
- Se solucionan problemas que no marcaban como visto los episodios/temporadas/serie.
- Se especifica más el texto cuando se instala pelisalacarta y si se quiere configurar la biblioteca de Kodi
> Fix "marcar como vistos" en la biblioteca

- python/main-classic/channels/estrenosgo.py
- python/main-classic/channels/estrenosgo.xml
modificado por cambios en la web
> Reparado canal EstrenosGo

- python/main-classic/channels/wopelis.py
- python/main-classic/channels/wopelis.xml
- python/main-classic/core/library.py
Version inicial de este canal de series y peliculas.
Incluye busqueda global por categorias (peliculas y series) y novedades en las mismas categorias
> Nuevo canal Wopelis

- python/main-classic/channels/cuelgame.py
- python/main-classic/channels/cuelgame.xml
- python/main-classic/channels/miltorrents.py
- python/main-classic/channels/miltorrents.xml
- python/main-classic/channels/pasateatorrent.py
- python/main-classic/channels/pasateatorrent.xml
- python/main-classic/channels/peliculasgratis.py
- python/main-classic/channels/peliculasgratis.xml
- python/main-classic/channels/torrentlocura.py
- python/main-classic/channels/torrentlocura.xml
- python/main-classic/channels/txibitsoft.py
- python/main-classic/channels/txibitsoft.xml
- python/main-classic/channels/verseriesonlinetv.py
- python/main-classic/channels/verseriesonlinetv.xml
- python/main-classic/channels/zentorrents.py
- python/main-classic/channels/zentorrents.xml
Cuelgame,Miltorrents,Pasateatorrent,Peliculasgratis,Torrentlocura,txbiso
ft ,Verseriesonlinetv y zentorrent
> Migración a Httptools paquete de canales

- python/main-classic/channels/cinefox.py
- python/main-classic/channels/cinefox.xml
Convertía videos de videogk a server vk pero el dominio videogk.com ya no existe
> Dominio videogk.com no existe para canal cinefox

- python/main-classic/channels/peliculasnu.py
- python/main-classic/channels/peliculasnu.xml
- python/main-classic/servers/dailymotion.py
- python/main-classic/servers/dailymotion.xml
- python/main-classic/servers/netutv.py
- python/main-classic/servers/netutv.xml
- python/main-classic/servers/openload.py
- python/main-classic/servers/openload.xml
...what else? :laughing: 
- Añadido en netutv la detección de subtítulos incrustados.
> Arreglado Openload... (netu y dailymotion)

- python/main-classic/channels/animeflv.py
- python/main-classic/channels/animeflv.xml
- python/main-classic/channels/animeflv_ru.py
- python/main-classic/channels/animeflv_ru.xml
- python/main-classic/channels/pelispedia.py
- python/main-classic/channels/pelispedia.xml
> fix pelispedia, animeflv.net, animeflv.ru

- python/main-classic/core/httptools.py
> Error ortográfico en httptools

- python/main-classic/channels/descargasmix.py
- python/main-classic/channels/descargasmix.xml
- python/main-classic/channels/peliculasnu.py
- python/main-classic/channels/peliculasnu.xml
- python/main-classic/channels/playmax.py
- python/main-classic/servers/filez.py
- python/main-classic/servers/filez.xml
- python/main-classic/servers/openload.py
- python/main-classic/servers/openload.xml
Por cambios en la página
Arreglados también los conectores openload y filez, y los canales peliculasnu y playmax
> Arreglado descargasmix (y openload, peliculasnu, filez...)

- python/main-classic/servers/spruto.py
- python/main-classic/servers/spruto.xml
Para que detecte código de servidor 503
> Actualizado spruto

- python/main-classic/channels/descargasmix.py
- python/main-classic/channels/descargasmix.xml
- python/main-classic/channels/divxatope.py
- python/main-classic/channels/divxatope.xml
- python/main-classic/channels/mejortorrent.py
- python/main-classic/channels/mejortorrent.xml
- python/main-classic/channels/newpct1.py
- python/main-classic/channels/newpct1.xml
- python/main-classic/channels/playmax.py
- python/main-classic/channels/playmax.xml
- Descargasmix: Por cambio de dominio.
- Divxatope, mejortorrent y newpct1: Reparados por cambios en varias secciones.
- Playmax: Error en algunos índices que se quedaron sin reparar.
> Arreglos en varios canales

- python/main-classic/channels/cumlouder.py
- python/main-classic/channels/cumlouder.xml
- python/main-classic/channels/freecambay.py
- python/main-classic/channels/freecambay.xml
- python/main-classic/channels/javtasty.py
- python/main-classic/channels/javtasty.xml
- python/main-classic/channels/pornhub.py
- python/main-classic/channels/pornhub.xml
- python/main-classic/channels/porntrex.py
- python/main-classic/channels/porntrex.xml
- python/main-classic/channels/vidz7.py
- python/main-classic/channels/vidz7.xml
- python/main-classic/servers/kingvid.py
- python/main-classic/servers/kingvid.xml
- python/main-classic/servers/openload.py
- python/main-classic/servers/openload.xml
- python/main-classic/servers/rapidvideo.py
- python/main-classic/servers/rapidvideo.xml
- python/main-classic/servers/streamango.py
- python/main-classic/servers/streamango.xml
- python/main-classic/servers/streamplay.py
- python/main-classic/servers/streamplay.xml
- python/main-classic/servers/vidzi.py
- Openload, streamplay y vidzi por cambios en el servidor.
- Nuevos conectores kingvid y streamango
- Reparado rapidvideo, usa proxy si falla por https
Canales adultos:
- Nuevos: freecambay, porntrex y javtasty
- Reparados: pornhub, cumlouder y vidz7
> Corregido openload y vidzi, nuevo conector streamango y kingvid, canales adultos

- python/main-classic/servers/flashx.py
- python/main-classic/servers/gamovideo.py
- python/main-classic/servers/gamovideo.xml
gamovideo: Mensaje detectado en: Cinefox - Novedades - Comanchería - Enlaces online
flashx: Actualizado mensaje para archivo borrado.
> Actualizado gamovideo, flashx

- python/main-classic/channels/alltorrent.py
- python/main-classic/channels/alltorrent.xml
- python/main-classic/channels/borrachodetorrent.py
- python/main-classic/channels/borrachodetorrent.xml
- python/main-classic/channels/divxtotal.py
- python/main-classic/channels/divxtotal.xml
- python/main-classic/channels/peliculasdk.py
- python/main-classic/channels/ver-pelis.py
- python/main-classic/channels/ver-pelis.xml
Alltorrent,Borrachotorrent,Divxtotal y Ver-pelis
PelículasDK:Añadida opción biblioteca
> Cuatro nuevos canales y mejoras PelículasDK

- python/main-classic/channels/pelis24.py
- python/main-classic/channels/pelis24.xml
Adaptacion por cambio de dominio y estructura de la web.
> correccion pelis24

- python/main-classic/platformcode/launcher.py
evitar q se guarden las url del canal tengourl en la lista del buscador global
> Correccion bug buscador global

- python/main-classic/channels/zentorrents.py
- python/main-classic/channels/zentorrents.xml
> Fix Zentorrent

- python/main-classic/servers/allvid.py
- python/main-classic/servers/allvid.xml
Actualizado para usar httptools y para que detecte archivo borrado
> Actualizado allvid

- python/main-classic/channels/txibitsoft.py
- python/main-classic/channels/txibitsoft.xml
Workaround error certificado SSL en alguno OS.Mejoras sección de
películas y algunos cambios código
> Fix Txibitsoft

- python/main-classic/channels/seodiv.py
- python/main-classic/channels/seodiv.xml
- python/main-classic/channels/ultrapeliculashd.py
- python/main-classic/channels/ultrapeliculashd.xml
Por cambio de la estructura de la pagina.
> Fix UltraPeliculasHD, SeoDiv

- python/main-classic/channels/cumlouder.py
- python/main-classic/channels/cumlouder.xml
- python/main-classic/channels/descargasmix.py
- python/main-classic/channels/pordede.py
- python/main-classic/channels/pordede.xml
- python/main-classic/channels/puyasubs.py
- python/main-classic/channels/puyasubs.xml
- python/main-classic/servers/gamovideo.py
- python/main-classic/servers/gamovideo.xml
- python/main-classic/servers/okru.py
- python/main-classic/servers/okru.xml
- python/main-classic/servers/rapidvideo.py
- python/main-classic/servers/rapidvideo.xml
- Conectores: Gamovideo (error con el user-agent), okru (cambio en la url embebida) y rapidvideo (mejorado regex de deteccion)
- Canales: Pordede (arreglada seccion siguientes capitulos), puyasubs (cambios en listado de torrents y regex) y cumlouder (fallaba en Kodi 17).
> Reparados varios canales y conectores

- python/main-classic/platformcode/platformtools.py
Al cambiar los valores de los settings generales se ha quedado sin modificar estos en platformtools y no funcionaban correctamente.
> Cambio de settings pendiente en platformtools

- python/main-classic/channels/estrenosgo.py
- python/main-classic/channels/estrenosgo.xml
- python/main-classic/channels/wopelis.py
- python/main-classic/channels/wopelis.xml
- Estrenosgo: compatibilidad con versiones python anteriores a la 2.7 Gracias a @SeiTaN  y @CmosGit mos por las indicaciones.
- Wopelis: Reparada funcion findvideos. Gracias al [foro ](http://www.mimediacenter.info/foro/viewtopic.php?f=6&t=11690)por el reporte de errores
> Correciones canales: Estrenosgo y Wopelis

- python/main-classic/core/servertools.py
- python/main-classic/platformcode/platformtools.py
- python/main-classic/servers/fastplay.xml
- python/main-classic/servers/okru.xml
Actualizados servidores fastplay y okru porque los patrones no estaban actalizados
> actualizados patrones fastplay y okru

- python/main-classic/channels/configuracion.py
- python/main-classic/core/servertools.py
- python/main-classic/servers/crunchyroll.xml
- python/main-classic/servers/debriders/alldebrid.xml
- python/main-classic/servers/filesmonster.xml
- python/main-classic/servers/nowvideo.xml
- python/main-classic/servers/onefichier.xml
- python/main-classic/servers/uploadedto.xml
Añadido parámetro 'default' en los controles de los servidores para user y password que faltaban y producían que la versión mediaserver mostrara 'null'
> Corregidos varios xmls

- python/main-classic/channels/descargas.py
- python/main-classic/channels/descargas.xml
- python/main-classic/core/downloader.py
- python/main-classic/platformcode/xbmc_config_menu.py
Mejorado canal descargas:
- Mas opciones de configuración según el sistema/conexión de cada uno en menú ajustes
- Tamaño por bloque (tamaño que descarga en cada ciclo del loop)
- Tamaño por parte (tamaño que almacena en memoria hasta que es escrito en el disco y reinicia la conexión)
- Conexiones simultaneas (conexiones máximas descargando a la vez)
-  Numero partes en memoria (numero de partes completadas en memoria pendientes de ser escritas en el disco, si se supera no se iniciaran nuevas partes hasta que las pendientes finalicen y se escriban en el disco para evitar que el dispositivo se quede sin memoria)
- Solucionado error para descargas en Android superiores a 2GB
- Permite elegir el servidor desde el que descargar, o hacerlo en modo automático
- si esta en modo automático …
> Mejora descargas

- python/main-classic/channels/ver-pelis.xml
- python/main-classic/resources/settings.xml
- python/version-mediaserver/resources/settings.xml
Corregido error en settings.xml
> fix settings.xml

- python/main-classic/lib/megaserver/client.py
- python/main-classic/lib/megaserver/handler.py
Correcciones menores para algunos enlaces muy concretos que fallan (nombres de archivos con Ñ)
> Fix librería megaserver

- python/main-classic/channels/buscador.py
Mostrar porcentaje al guardar los canales incluidos en la busqueda. 
Gracias @SeiTaN por avisarme
> Fix Buscador Global

- python/main-classic/channels/allpeliculas.py
- python/main-classic/channels/allpeliculas.xml
- python/main-classic/channels/pelispedia.py
- python/main-classic/channels/pelispedia.xml
- python/main-classic/servers/fastplay.py
- python/main-classic/servers/fastplay.xml
- python/main-classic/servers/powvideo.py
- python/main-classic/servers/powvideo.xml
- python/main-classic/servers/streamplay.py
- python/main-classic/servers/streamplay.xml
fastplay: reparado subtitulos.
pelispedia: para reconocer server raptu
powvideo y streamplay reparado por @r0balo 
Allpeliculas: reparado búsqueda de videos
> Actualizado fastplay, pelispedia, powvideo, streamplay, allpeliculas

- python/main-classic/channels/anitoonstv.py
- python/main-classic/channels/anitoonstv.xml
- python/main-classic/channels/cartoonlatino.py
- python/main-classic/channels/cartoonlatino.xml
- python/main-classic/channels/seriesmeme.py
Nuevos canales:
AnitoonsTV
Cartoon-Latino
SeriesMeme:
Arreglados detalles estéticos 
Agregado modulo tmdb para mejorar estética de series
> Nuevos canales y detalles menores en canales creados

- python/main-classic/servers/fastplay.xml
- python/main-classic/servers/filescdn.py
- python/main-classic/servers/filescdn.xml
- python/main-classic/servers/powvideo.py
- python/main-classic/servers/powvideo.xml
- python/main-classic/servers/streamplay.py
- python/main-classic/servers/streamplay.xml
- python/main-classic/servers/userscloud.py
filescdn: Actualizado patrón del get_video
powvideo y streamplay: Reparado por @r0balo 
fastplay: Patrón reparado
> Actualizado filescdn, powvideo, streamplay, fastplay, userscloud

- python/main-classic/channels/autoplay.py
- python/main-classic/channels/cinecalidad.py
- python/main-classic/channels/cinecalidad.xml
- python/main-classic/channels/doomtv.py
- python/main-classic/channels/doomtv.xml
- python/main-classic/channels/locopelis.py
- python/main-classic/channels/locopelis.xml
- python/main-classic/channels/metaserie.py
- python/main-classic/channels/metaserie.xml
- python/main-classic/channels/mundoflv.py
- python/main-classic/channels/mundoflv.xml
- python/main-classic/channels/pelisplus.py
- python/main-classic/channels/pelisplus.xml
- python/main-classic/channels/seodiv.py
- python/main-classic/channels/seodiv.xml
- python/main-classic/channels/verpeliculasnuevas.py
- python/main-classic/channels/verpeliculasnuevas.xml
Bueno en vistas de una inminente salida en estos dias de la proxima version que incluye el modulo AutoPlay, dejo estos canales que estan adaptados para funcionar con dicho modulo.
> [4.3] Canales con AutoPlay

- python/main-classic/servers/openload.py
> Arreglado openload

- python/main-classic/channels/borrachodetorrent.py
- python/main-classic/channels/borrachodetorrent.xml
- python/main-classic/channels/cuelgame.py
- python/main-classic/channels/cuelgame.xml
- python/main-classic/channels/divxtotal.py
- python/main-classic/channels/miltorrents.py
- python/main-classic/channels/miltorrents.xml
- python/main-classic/channels/pasateatorrent.py
- python/main-classic/channels/pasateatorrent.xml
- python/main-classic/channels/peliculasdk.py
- python/main-classic/channels/peliculasdk.xml
- python/main-classic/channels/peliscon.py
- python/main-classic/channels/peliscon.xml
- python/main-classic/channels/torrentlocura.py
- python/main-classic/channels/torrentlocura.xml
- python/main-classic/channels/txibitsoft.py
- python/main-classic/channels/txibitsoft.xml
- python/main-classic/channels/ver-pelis.py
- python/main-classic/channels/ver-pelis.xml
- python/main-classic/channels/verseriesonlinetv.py
- python/main-classic/channels/verseriesonlinetv.xml
- python/main-classic/channels/zentorrents.py
- python/main-classic/channels/zentorrents.xml
Nuevo canal Peliscon y reparación de infinitud de canales
> Fix_multitud de canales y nuevo canal

- python/main-classic/channels/buscador.py
- python/main-classic/channels/cinetux.py
- python/main-classic/channels/cinetux.xml
- python/main-classic/channels/vernovelasonline.py
- python/main-classic/channels/vernovelasonline.xml
- python/main-classic/core/channeltools.py
- python/main-classic/servers/downace.py
- python/main-classic/servers/downace.xml
- python/main-classic/servers/gamovideo.py
- python/main-classic/servers/gamovideo.xml
- python/main-classic/servers/netutv.xml
- python/main-classic/servers/powvideo.py
- python/main-classic/servers/streamplay.py
Buscador global: Bug y errores en el log reparado por @superberny70 
Nuevo canal: Ver novelas online
Nuevo conector:  downace
streamplay y powvideo: reparado por @r0balo 
gamovideo: Actualizado get_url_video
netutv: Patrón actualizado
cinutux:  Reparado por cambio de estructura en la pagina
> Bug: buscador global, nuevo canal, nuevo conector. Reparado powvideo, streamplay, gamovideo, netutv, cinetux

- python/main-classic/channels/peliscon.py
- python/main-classic/channels/peliscon.xml
- python/main-classic/channels/torrentlocura.py
- python/main-classic/channels/torrentlocura.xml
Peliscon:
Fix paginación y ultimos capitulos en series.
Torrenlocura:
Corrección por cambios en  la web.
> Fix Torrentlocura y Peliscon

- python/main-classic/core/library.py
> Arregla el multisource

- python/main-classic/channels/animeflv.py
- python/main-classic/channels/animeflv.xml
- python/main-classic/channels/animeflv_me.py
- python/main-classic/channels/animeflv_me.xml
- python/main-classic/channels/animeflv_ru.py
- python/main-classic/channels/animeflv_ru.xml
- python/main-classic/channels/anitoonstv.py
- python/main-classic/channels/anitoonstv.xml
- python/main-classic/channels/cartoonlatino.py
- python/main-classic/channels/cartoonlatino.xml
- python/main-classic/channels/serieslan.py
- python/main-classic/channels/serieslan.xml
- python/main-classic/channels/seriesmeme.py
- python/main-classic/channels/seriesmeme.xml
- python/main-classic/channels/verpelis.py
- python/main-classic/channels/verpelis.xml
Mejoras de compatibilidad con mediaserver y plex
> Añadida compatibilidad para plex y mediaserver en todos los canales con renumbertool

- python/main-classic/channels/plusdede.py
- python/main-classic/channels/plusdede.xml
Port de canal Pordede, nueva web clon plusdede
> Canal Plusdede (Port de pordede, clon)
